ROOT_DIR = ../../..
JAVAC = javac
JAVA = java
JAVACFLAGS += source 1.4
PACKAGE_NAME = maspack.geometry

PACKAGE_JAVA_FILES = 

JAVA_SUBDIRS = io

JAVA_TEST_PROGRAMS = \
	AffineTransformerTest \
	BVBoxNodeTest \
	BVBoxNodeTesterTest \
	BVFeatureQueryTest \
	BVIntersectorTest \
	BVTreeTest \
	ConvexPolygon3dTest \
	ConvexPolygonIntersectorTest \
	DeformationTransformerTest \
	DelaunayInterpolatorTest \
	DistanceGridTest \
	FaceTest \
	GeometryUtilsTest \
	HalfEdgeTest \
	MeshFactoryTest \
	MeshRayIntersectionTest \
	MeshUtilitiesTest \
	NagataInterpolatorTest \
	Polygon2dTest \
	Polygon3dTest \
	Polygon3dCalcTest \
	PolygonIntersectorTest \
	PolygonalMeshTest \
	PolylineMeshTest \
	PointMeshTest \
	QuadraticUtilsTest \
	RigidTransformerTest \
	RobustPredsTest \
	ScalarGridTest \
	TetgenConvexHullTest \
	TetgenTessellatorTest \
	VectorGridTest \
	Vertex3dListTest \
	Vertex3dTest \
	WindingCalculatorTest

OTHER_CLASSES = 

default: build

CLASSES:: $(PACKAGE_CLASSES) $(OTHER_CLASSES)

-include $(ROOT_DIR)/Makefile.base

