ROOT_DIR = ../../../..
JAVAC = javac
JAVA = java
PACKAGE_NAME = maspack.geometry.io

PACKAGE_JAVA_FILES = 

JAVA_TEST_PROGRAMS = \
	PlyReaderWriterTest \
	WavefrontReaderTest 

OTHER_CLASSES = 

default: build

CLASSES:: $(PACKAGE_CLASSES) $(OTHER_CLASSES)

-include $(ROOT_DIR)/Makefile.base
