ROOT_DIR = ../../..
PACKAGE_NAME = maspack.fileutil

PACKAGE_JAVA_FILES = 

JAVA_TEST_PROGRAMS = \
	NativeLibraryManagerTest

OTHER_CLASSES = 

default: build

CLASSES:: $(PACKAGE_CLASSES)  $(OTHER_CLASSES)

-include $(ROOT_DIR)/Makefile.base
