ROOT_DIR = ../../..
PACKAGE_NAME = maspack.interpolation

JAVA_SUBDIRS =

PACKAGE_JAVA_FILES = 

JAVA_TEST_PROGRAMS = \
	NumericListTest \
	CubicHermiteSpline1dTest \
	CubicHermiteSpline3dTest \
	LinearSpline3dTest \
	LinearSpline1dTest

default: build

-include $(ROOT_DIR)/Makefile.base
