ROOT_DIR = ../../..
PACKAGE_NAME = maspack.properties

JAVA_SUBDIRS =

PACKAGE_JAVA_FILES = 

JAVA_TEST_PROGRAMS = \
	PropertyDescTest \
	PropertyTest \
	EditTest 

default: build

-include $(ROOT_DIR)/Makefile.base
