ROOT_DIR = ../../../..
PACKAGE_NAME = artisynth.core.modeltest

JAVA_SUBDIRS =

PACKAGE_JAVA_FILES =

JAVA_TEST_PROGRAMS = \
	TransformGeometryTest \
	AttachmentTest

default: build

-include $(ROOT_DIR)/Makefile.base
