# ArtisynthScript: "wrappingTest"
#
from java.io import File
from maspack.geometry.DistanceGrid import DistanceMethod
DistanceGrid.DEFAULT_DISTANCE_METHOD = DistanceMethod.BVH # more accurate
main.maskFocusStealing (True)
File("devinfo.txt").delete()
loadModel ("artisynth.demos.wrapping.GeneralWrapTest", "-geo", "CYLINDER")
System.out.println ("CYLINDER")
run(10)
waitForStop()
loadModel ("artisynth.demos.wrapping.GeneralWrapTest", "-geo", "SPHERE")
System.out.println ("SPHERE")
run(10)
waitForStop()
loadModel ("artisynth.demos.wrapping.GeneralWrapTest", "-geo", "ELLIPSOID")
System.out.println ("ELLIPSOID")
run(10)
waitForStop()
loadModel ("artisynth.demos.wrapping.GeneralWrapTest", "-geo", "TORUS")
System.out.println ("TORUS")
run(10)
waitForStop()
loadModel ("artisynth.demos.wrapping.GeneralWrapTest", "-geo", "CYLINDER", "-mesh")
System.out.println ("CYLINDER GRID")
run(10)
waitForStop()
loadModel ("artisynth.demos.wrapping.GeneralWrapTest", "-geo", "SPHERE", "-mesh")
System.out.println ("SPHERE GRID")
run(10)
waitForStop()
loadModel ("artisynth.demos.wrapping.GeneralWrapTest", "-geo", "ELLIPSOID", "-mesh")
System.out.println ("ELLIPSOID GRID")
run(10)
waitForStop()
loadModel ("artisynth.demos.wrapping.GeneralWrapTest", "-geo", "TORUS", "-mesh")
System.out.println ("TORUS GRID")
run(10)
waitForStop()
loadModel ("artisynth.demos.wrapping.GeneralWrapTest", "-geo", "TALUS")
System.out.println ("TALUS")
run(10)
waitForStop()
loadModel ("artisynth.demos.wrapping.GeneralWrapTest", "-geo", "TALUS", 
           "-wrapDamping", "20", "-maxWrapIterations", "20")
System.out.println ("TALUS 20 20")
run(10)
waitForStop()
loadModel ("artisynth.demos.wrapping.GeneralWrapTest", "-geo", "PHALANX")
System.out.println ("PHALANX")
run(10)
waitForStop()
loadModel ("artisynth.demos.wrapping.GeneralWrapTest", "-geo", "HUMERUS",
           "-wrapDamping", "20")
System.out.println ("HUMERUS")
run(10)
waitForStop()
loadModel ("artisynth.demos.wrapping.GeneralWrapTest", "-geo", "HIP",
           "-wrapDamping", "20", "-maxWrapIterations", "20")
System.out.println ("HIP 20 20")
run(10)
waitForStop()

if main.getViewer() == None:
   quit()

