ROOT_DIR = ../../../..
PACKAGE_NAME = artisynth.core.modelbase

JAVA_SUBDIRS =

PACKAGE_JAVA_FILES = 

JAVA_TEST_PROGRAMS = \
	ComponentTest \
	ScannableListTest
	# DependencyClosureTest \

default: build

-include $(ROOT_DIR)/Makefile.base
