ROOT_DIR = ../../..
JAVAC = javac
JAVA = java
JAVACFLAGS += source 1.4
PACKAGE_NAME = maspack.numerics

PACKAGE_JAVA_FILES = 

JAVA_TEST_PROGRAMS = \
	PolynomialFitTest

OTHER_CLASSES = 

default: build

CLASSES:: $(PACKAGE_CLASSES)  $(OTHER_CLASSES)

-include $(ROOT_DIR)/Makefile.base
