ROOT_DIR = ../../..
PACKAGE_NAME = artisynth.core

JAVA_SUBDIRS = \
	driver \
	femmodels \
	gui \
	mechmodels \
	modelbase \
	moviemaker \
	probes \
	util

default: build

-include $(ROOT_DIR)/Makefile.base
