ROOT_DIR = ../../..
PACKAGE_NAME = maspack.function

PACKAGE_JAVA_FILES = 

JAVA_TEST_PROGRAMS = \
	ConstantFunction1x1Test \
	LinearFunctionNx1Test \
	PolyFunction1x1Test

OTHER_CLASSES = 

default: build

-include $(ROOT_DIR)/Makefile.base
