/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class maspack_solvers_UmfpackSolver */

#ifndef _Included_maspack_solvers_UmfpackSolver
#define _Included_maspack_solvers_UmfpackSolver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     maspack_solvers_UmfpackSolver
 * Method:    umfpack_di_symbolic
 * Signature: (II[I[I[D[I[D[D)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_UmfpackSolver_umfpack_1di_1symbolic
  (JNIEnv *, jobject, jint, jint, jintArray, jintArray, jdoubleArray, jintArray, jdoubleArray, jdoubleArray);

/*
 * Class:     maspack_solvers_UmfpackSolver
 * Method:    umfpack_di_numeric
 * Signature: ([I[I[D[I[I[D[D)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_UmfpackSolver_umfpack_1di_1numeric
  (JNIEnv *, jobject, jintArray, jintArray, jdoubleArray, jintArray, jintArray, jdoubleArray, jdoubleArray);

/*
 * Class:     maspack_solvers_UmfpackSolver
 * Method:    umfpack_di_solve
 * Signature: (I[I[I[D[D[D[I[D[D)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_UmfpackSolver_umfpack_1di_1solve
  (JNIEnv *, jobject, jint, jintArray, jintArray, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jdoubleArray, jdoubleArray);

/*
 * Class:     maspack_solvers_UmfpackSolver
 * Method:    umfpack_di_free_symbolic
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_maspack_solvers_UmfpackSolver_umfpack_1di_1free_1symbolic
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     maspack_solvers_UmfpackSolver
 * Method:    umfpack_di_free_numeric
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_maspack_solvers_UmfpackSolver_umfpack_1di_1free_1numeric
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     maspack_solvers_UmfpackSolver
 * Method:    umfpack_di_defaults
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_maspack_solvers_UmfpackSolver_umfpack_1di_1defaults
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
