/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class maspack_solvers_PardisoSolver */

#ifndef _Included_maspack_solvers_PardisoSolver
#define _Included_maspack_solvers_PardisoSolver
#ifdef __cplusplus
extern "C" {
#endif
#undef maspack_solvers_PardisoSolver_ERR_INCONSISTENT_INPUT
#define maspack_solvers_PardisoSolver_ERR_INCONSISTENT_INPUT -1L
#undef maspack_solvers_PardisoSolver_ERR_MEMORY
#define maspack_solvers_PardisoSolver_ERR_MEMORY -2L
#undef maspack_solvers_PardisoSolver_ERR_REORDERING
#define maspack_solvers_PardisoSolver_ERR_REORDERING -3L
#undef maspack_solvers_PardisoSolver_ERR_NUMERICAL
#define maspack_solvers_PardisoSolver_ERR_NUMERICAL -4L
#undef maspack_solvers_PardisoSolver_ERR_INTERNAL
#define maspack_solvers_PardisoSolver_ERR_INTERNAL -5L
#undef maspack_solvers_PardisoSolver_ERR_PREORDERING
#define maspack_solvers_PardisoSolver_ERR_PREORDERING -6L
#undef maspack_solvers_PardisoSolver_ERR_DIAGONAL
#define maspack_solvers_PardisoSolver_ERR_DIAGONAL -7L
#undef maspack_solvers_PardisoSolver_ERR_INT_OVERFLOW
#define maspack_solvers_PardisoSolver_ERR_INT_OVERFLOW -8L
#undef maspack_solvers_PardisoSolver_ERR_NO_LICENCE
#define maspack_solvers_PardisoSolver_ERR_NO_LICENCE -10L
#undef maspack_solvers_PardisoSolver_ERR_LICENCE_EXPIRED
#define maspack_solvers_PardisoSolver_ERR_LICENCE_EXPIRED -11L
#undef maspack_solvers_PardisoSolver_ERR_WRONG_USERHOST
#define maspack_solvers_PardisoSolver_ERR_WRONG_USERHOST -12L
#undef maspack_solvers_PardisoSolver_ERR_CGS_UNSTABLE_RESIDUAL
#define maspack_solvers_PardisoSolver_ERR_CGS_UNSTABLE_RESIDUAL -21L
#undef maspack_solvers_PardisoSolver_ERR_CGS_SLOW_CONVERGENCE
#define maspack_solvers_PardisoSolver_ERR_CGS_SLOW_CONVERGENCE -22L
#undef maspack_solvers_PardisoSolver_ERR_CGS_ITERATION_LIMIT
#define maspack_solvers_PardisoSolver_ERR_CGS_ITERATION_LIMIT -23L
#undef maspack_solvers_PardisoSolver_ERR_CGS_PERTURBED_PIVOTS
#define maspack_solvers_PardisoSolver_ERR_CGS_PERTURBED_PIVOTS -24L
#undef maspack_solvers_PardisoSolver_ERR_CGS_FACTORIZATION_TOO_FAST
#define maspack_solvers_PardisoSolver_ERR_CGS_FACTORIZATION_TOO_FAST -25L
#undef maspack_solvers_PardisoSolver_ERR_ITERATION_LIMIT
#define maspack_solvers_PardisoSolver_ERR_ITERATION_LIMIT -100L
#undef maspack_solvers_PardisoSolver_ERR_ITERATION_CONVERGENCE
#define maspack_solvers_PardisoSolver_ERR_ITERATION_CONVERGENCE -101L
#undef maspack_solvers_PardisoSolver_ERR_ITERATION_ERROR
#define maspack_solvers_PardisoSolver_ERR_ITERATION_ERROR -102L
#undef maspack_solvers_PardisoSolver_ERR_ITERATION_BREAKDOWN
#define maspack_solvers_PardisoSolver_ERR_ITERATION_BREAKDOWN -103L
#undef maspack_solvers_PardisoSolver_ERR_CANT_LOAD_LIBRARIES
#define maspack_solvers_PardisoSolver_ERR_CANT_LOAD_LIBRARIES -1000L
#undef maspack_solvers_PardisoSolver_INIT_UNKNOWN
#define maspack_solvers_PardisoSolver_INIT_UNKNOWN 0L
#undef maspack_solvers_PardisoSolver_INIT_LIBRARIES_LOADED
#define maspack_solvers_PardisoSolver_INIT_LIBRARIES_LOADED 1L
#undef maspack_solvers_PardisoSolver_INIT_OK
#define maspack_solvers_PardisoSolver_INIT_OK 2L
#undef maspack_solvers_PardisoSolver_AMD_REORDER
#define maspack_solvers_PardisoSolver_AMD_REORDER 0L
#undef maspack_solvers_PardisoSolver_METIS_REORDER
#define maspack_solvers_PardisoSolver_METIS_REORDER 2L
#undef maspack_solvers_PardisoSolver_METIS_REORDER_PARALLEL
#define maspack_solvers_PardisoSolver_METIS_REORDER_PARALLEL 3L
#undef maspack_solvers_PardisoSolver_UNSET
#define maspack_solvers_PardisoSolver_UNSET 0L
#undef maspack_solvers_PardisoSolver_ANALYZED
#define maspack_solvers_PardisoSolver_ANALYZED 1L
#undef maspack_solvers_PardisoSolver_FACTORED
#define maspack_solvers_PardisoSolver_FACTORED 2L
#undef maspack_solvers_PardisoSolver_RET_OK
#define maspack_solvers_PardisoSolver_RET_OK 0L
/*
 * Class:     maspack_solvers_PardisoSolver
 * Method:    doInit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_maspack_solvers_PardisoSolver_doInit
  (JNIEnv *, jobject);

/*
 * Class:     maspack_solvers_PardisoSolver
 * Method:    doGetInitError
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_PardisoSolver_doGetInitError
  (JNIEnv *, jobject, jlong);

/*
 * Class:     maspack_solvers_PardisoSolver
 * Method:    doGetNumThreads
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_PardisoSolver_doGetNumThreads
  (JNIEnv *, jobject, jlong);

/*
 * Class:     maspack_solvers_PardisoSolver
 * Method:    doSetNumThreads
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_PardisoSolver_doSetNumThreads
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     maspack_solvers_PardisoSolver
 * Method:    doGetNumNonZerosInFactors
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_PardisoSolver_doGetNumNonZerosInFactors
  (JNIEnv *, jobject, jlong);

/*
 * Class:     maspack_solvers_PardisoSolver
 * Method:    doGetNumNegEigenvalues
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_PardisoSolver_doGetNumNegEigenvalues
  (JNIEnv *, jobject, jlong);

/*
 * Class:     maspack_solvers_PardisoSolver
 * Method:    doGetNumPosEigenvalues
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_PardisoSolver_doGetNumPosEigenvalues
  (JNIEnv *, jobject, jlong);

/*
 * Class:     maspack_solvers_PardisoSolver
 * Method:    doGetNumPerturbedPivots
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_PardisoSolver_doGetNumPerturbedPivots
  (JNIEnv *, jobject, jlong);

/*
 * Class:     maspack_solvers_PardisoSolver
 * Method:    doGetSPDZeroPivot
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_PardisoSolver_doGetSPDZeroPivot
  (JNIEnv *, jobject, jlong);

/*
 * Class:     maspack_solvers_PardisoSolver
 * Method:    doGetPeakAnalysisMemoryUsage
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_PardisoSolver_doGetPeakAnalysisMemoryUsage
  (JNIEnv *, jobject, jlong);

/*
 * Class:     maspack_solvers_PardisoSolver
 * Method:    doGetAnalysisMemoryUsage
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_PardisoSolver_doGetAnalysisMemoryUsage
  (JNIEnv *, jobject, jlong);

/*
 * Class:     maspack_solvers_PardisoSolver
 * Method:    doGetFactorSolveMemoryUsage
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_PardisoSolver_doGetFactorSolveMemoryUsage
  (JNIEnv *, jobject, jlong);

/*
 * Class:     maspack_solvers_PardisoSolver
 * Method:    doGetMaxRefinementSteps
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_PardisoSolver_doGetMaxRefinementSteps
  (JNIEnv *, jobject, jlong);

/*
 * Class:     maspack_solvers_PardisoSolver
 * Method:    doSetMaxRefinementSteps
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_PardisoSolver_doSetMaxRefinementSteps
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     maspack_solvers_PardisoSolver
 * Method:    doGetNumRefinementSteps
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_PardisoSolver_doGetNumRefinementSteps
  (JNIEnv *, jobject, jlong);

/*
 * Class:     maspack_solvers_PardisoSolver
 * Method:    doGetReorderMethod
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_PardisoSolver_doGetReorderMethod
  (JNIEnv *, jobject, jlong);

/*
 * Class:     maspack_solvers_PardisoSolver
 * Method:    doSetReorderMethod
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_PardisoSolver_doSetReorderMethod
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     maspack_solvers_PardisoSolver
 * Method:    doGetPivotPerturbation
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_PardisoSolver_doGetPivotPerturbation
  (JNIEnv *, jobject, jlong);

/*
 * Class:     maspack_solvers_PardisoSolver
 * Method:    doSetPivotPerturbation
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_PardisoSolver_doSetPivotPerturbation
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     maspack_solvers_PardisoSolver
 * Method:    doGetApplyScaling
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_PardisoSolver_doGetApplyScaling
  (JNIEnv *, jobject, jlong);

/*
 * Class:     maspack_solvers_PardisoSolver
 * Method:    doSetApplyScaling
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_PardisoSolver_doSetApplyScaling
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     maspack_solvers_PardisoSolver
 * Method:    doGetApplyWeightedMatchings
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_PardisoSolver_doGetApplyWeightedMatchings
  (JNIEnv *, jobject, jlong);

/*
 * Class:     maspack_solvers_PardisoSolver
 * Method:    doSetApplyWeightedMatchings
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_PardisoSolver_doSetApplyWeightedMatchings
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     maspack_solvers_PardisoSolver
 * Method:    doGetUse2x2Pivoting
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_PardisoSolver_doGetUse2x2Pivoting
  (JNIEnv *, jobject, jlong);

/*
 * Class:     maspack_solvers_PardisoSolver
 * Method:    doSetUse2x2Pivoting
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_PardisoSolver_doSetUse2x2Pivoting
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     maspack_solvers_PardisoSolver
 * Method:    doGetMatrixChecking
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_PardisoSolver_doGetMatrixChecking
  (JNIEnv *, jobject, jlong);

/*
 * Class:     maspack_solvers_PardisoSolver
 * Method:    doSetMatrixChecking
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_PardisoSolver_doSetMatrixChecking
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     maspack_solvers_PardisoSolver
 * Method:    doGetMessageLevel
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_PardisoSolver_doGetMessageLevel
  (JNIEnv *, jobject, jlong);

/*
 * Class:     maspack_solvers_PardisoSolver
 * Method:    doSetMessageLevel
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_PardisoSolver_doSetMessageLevel
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     maspack_solvers_PardisoSolver
 * Method:    doSetMatrix
 * Signature: (J[D[I[III)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_PardisoSolver_doSetMatrix
  (JNIEnv *, jobject, jlong, jdoubleArray, jintArray, jintArray, jint, jint);

/*
 * Class:     maspack_solvers_PardisoSolver
 * Method:    doSetSPDMatrix
 * Signature: (J[D[I[III)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_PardisoSolver_doSetSPDMatrix
  (JNIEnv *, jobject, jlong, jdoubleArray, jintArray, jintArray, jint, jint);

/*
 * Class:     maspack_solvers_PardisoSolver
 * Method:    doSetSymmetricMatrix
 * Signature: (J[D[I[III)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_PardisoSolver_doSetSymmetricMatrix
  (JNIEnv *, jobject, jlong, jdoubleArray, jintArray, jintArray, jint, jint);

/*
 * Class:     maspack_solvers_PardisoSolver
 * Method:    doFactorMatrix
 * Signature: (J[D)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_PardisoSolver_doFactorMatrix__J_3D
  (JNIEnv *, jobject, jlong, jdoubleArray);

/*
 * Class:     maspack_solvers_PardisoSolver
 * Method:    doFactorMatrix
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_PardisoSolver_doFactorMatrix__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     maspack_solvers_PardisoSolver
 * Method:    doSolve
 * Signature: (J[D[D)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_PardisoSolver_doSolve
  (JNIEnv *, jobject, jlong, jdoubleArray, jdoubleArray);

/*
 * Class:     maspack_solvers_PardisoSolver
 * Method:    doIterativeSolve
 * Signature: (J[D[D[DI)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_PardisoSolver_doIterativeSolve
  (JNIEnv *, jobject, jlong, jdoubleArray, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     maspack_solvers_PardisoSolver
 * Method:    doFactorAndSolve
 * Signature: (J[D[D[DI)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_PardisoSolver_doFactorAndSolve
  (JNIEnv *, jobject, jlong, jdoubleArray, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     maspack_solvers_PardisoSolver
 * Method:    doRelease
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_maspack_solvers_PardisoSolver_doRelease
  (JNIEnv *, jobject, jlong);

/*
 * Class:     maspack_solvers_PardisoSolver
 * Method:    doExit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_maspack_solvers_PardisoSolver_doExit
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
