#!/bin/bash
#
# Script to call 'make html' in all documentation subdirectories. We can't
# use make to do this, because for some reason when make descends into
# the subdirectory, some environment setting is changed that prevents
# math images from being created. The shell command called to create
# the math images seems to create an improperly formed TEXINPUTS
# environment variable, which in turn causes the error
#
# sh: :../texinputs:../../texinputs:: No such file or directory
#
SUBDIRS=`make echo_subdirs`
for dd in $SUBDIRS ; do
   if [ -d $dd ] ; then
      echo Running make html in $dd -- ;
      (cd $dd; make html)
   fi
done
