#!/bin/bash
usage() {
   echo "Usage: $0 [<cmpSuffix>]"
   exit 1
}
suffix="ref"
if [[ $# -eq 1 ]]; then
    suffix=$1
elif [[ $# -gt 1 ]]; then
    usage
fi
COMPSTATE="java artisynth.core.util.CompareStateFiles"
echo mechmodelTest
artisynth -noGui -script mechmodelTest.py &> log.allrun
$COMPSTATE mechmodelTest.out mechmodelTest.$suffix
echo inverseTest
artisynth -noGui -script inverseTest.py &>> log.allrun
$COMPSTATE inverseTest.out inverseTest.$suffix
echo wraptest
artisynth -noGui -script wraptest.py &>> log.allrun
$COMPSTATE wraptest.out wraptest.$suffix
echo contestAjl
artisynth -useAjlCollision -noGui -script contactTest.py [ contestAjl.out ] &>> log.allrun
$COMPSTATE contestAjl.out contestAjl.$suffix
echo contestReg
artisynth -noGui -script contactTest.py [ contestReg.out ] &>> log.allrun
$COMPSTATE contestReg.out contestReg.$suffix
echo femtest
artisynth -noGui -script femtest.py &>> log.allrun
$COMPSTATE femtest.out femtest.$suffix
echo skinningTest
artisynth -noGui -script skinningTest.py &>> log.allrun
$COMPSTATE skinningTest.out skinningTest.$suffix
