ROOT_DIR = ../../../..
PACKAGE_NAME = artisynth.core.gui

JAVA_SUBDIRS = timeline selectionManager navpanel jythonconsole widgets

PACKAGE_JAVA_FILES = 

default: build

-include $(ROOT_DIR)/Makefile.base
