
ROOT_DIR = ../../../..
PACKAGE_NAME = artisynth.core.materials

JAVA_SUBDIRS =

PACKAGE_JAVA_FILES =

JAVA_TEST_PROGRAMS = \
	FemMaterialTest \
	AxialMaterialTest

default: build

-include $(ROOT_DIR)/Makefile.base
