
ROOT_DIR = ../../../..
PACKAGE_NAME = artisynth.core.mechmodels

JAVA_SUBDIRS =

PACKAGE_JAVA_FILES = 

JAVA_TEST_PROGRAMS = \
	AxialSpringTest \
	CollisionHandlerTableTest \
	CollisionManagerTest \
        EBBeamBodyTest \
	FrameSpringTest \
	FrameTargetTest \
	MultiPointSpringTest \
	PointFrameAttachmentTest \
	PointParticleAttachmentTest \
	PointTargetTest \
	RigidBodyTest

default: build

-include $(ROOT_DIR)/Makefile.base
