
ROOT_DIR = ../../../..
PACKAGE_NAME = artisynth.core.mechmodels

JAVA_SUBDIRS =

PACKAGE_JAVA_FILES = 

JAVA_TEST_PROGRAMS = \
	CollisionManagerTest \
	AxialSpringTest

default: build

-include $(ROOT_DIR)/Makefile.base
