ROOT_DIR = ../../..
JAVAC = javac
JAVA = java
JAVACFLAGS += source 1.4
PACKAGE_NAME = maspack.matrix

PACKAGE_JAVA_FILES = 

JAVA_TEST_PROGRAMS = \
	AffineTransform3dTest \
	CholeskyDecompositionTest \
	LUDecompositionTest \
	Matrix2dTest \
	Matrix3dTest \
	Matrix4dTest \
	Matrix6dTest \
	Matrix3x6Test \
	Matrix6x3Test \
	MatrixNdTest \
	PlaneTest \
	PolarDecomposition3dTest \
	QRDecompositionTest \
	QRDecomposition3dTest \
	QuaternionTest \
	RigidTransform3dTest \
	RotationMatrix3dTest \
	SparseBlockMatrixTest \
	SparseNumberedBlockMatrixTest \
	SVDecompositionTest \
	SVDecomposition3dTest \
	Vector2dTest \
	Vector3dTest \
	Vector4dTest \
	VectorNdTest \
	VectorNiTest \
	SymmetricMatrix3dTest \
	SparseMatrixNdTest \
	SparseMatrixCRSTest \
	SparseVectorNdTest

OTHER_CLASSES = 

default: build

CLASSES:: $(PACKAGE_CLASSES)  $(OTHER_CLASSES)

-include $(ROOT_DIR)/Makefile.base
