ROOT_DIR = ../../..
JAVAC = javac
JAVA = java
JAVACFLAGS += source 1.4
PACKAGE_NAME = maspack.matrix

PACKAGE_JAVA_FILES = 

JAVA_TEST_PROGRAMS = \
	AffineTransform3dTest \
	AxisAlignedRotationTest \
	CholeskyDecompositionTest \
	DualQuaternionTest \
	EigenDecompositionTest \
	LUDecompositionTest \
	Matrix1x1Test \
	Matrix1x3Test \
	Matrix1x6Test \
	Matrix2dTest \
	Matrix2x3Test \
	Matrix2x6Test \
	Matrix3dTest \
	Matrix3x1Test \
	Matrix3x2Test \
	Matrix3x4Test \
	Matrix3x6Test \
	Matrix4dTest \
	Matrix4x3Test \
	Matrix6dTest \
	Matrix6x1Test \
	Matrix6x2Test \
	Matrix6x3Test \
	MatrixNdTest \
	PlaneTest \
	PolarDecomposition3dTest \
	QRDecompositionTest \
	QRDecomposition3dTest \
	QuaternionTest \
	RigidTransform3dTest \
	RotationMatrix3dTest \
	SVDecompositionTest \
	SVDecomposition3dTest \
	ScaledRigidTransform3dTest \
	SparseBlockMatrixTest \
	SparseMatrixCRSTest \
	SparseMatrixNdTest \
	SparseNumberedBlockMatrixTest \
	SparseVectorNdTest \
	SymmetricMatrix3dTest \
	Vector2dTest \
	Vector2iTest \
	Vector3dTest \
	Vector3iTest \
	Vector4dTest \
	VectorNdTest \
	VectorNiTest \

OTHER_CLASSES = 

default: build

CLASSES:: $(PACKAGE_CLASSES)  $(OTHER_CLASSES)

-include $(ROOT_DIR)/Makefile.base
