package maspack.matrix;

/**
 * Provides static methods to implement MatrixBlock.mulTransposeRightAdd()
 * NOTE: This code is machine generated by GenerateMulAdd
 */
public class MatrixMulTransposeRightAdd {

   public static void mulTransposeRightAdd1x1 (Matrix1x1 MR, Matrix M1, Matrix M2) {
      if (M1.rowSize() != 1 ||
          M2.rowSize() != 1 ||
          M1.colSize() != M2.colSize()) {
         throw new ImproperSizeException (
            "matrix sizes "+M1.getSize()+" and "+M2.getSize()+
            " do not conform to "+MR.getSize());
      }
      if (M1.isFixedSize() && M2.isFixedSize()) {
         switch (M1.colSize()) {
            case 1: {
               Matrix1x1 A = (Matrix1x1)M1;
               Matrix1x1 B = (Matrix1x1)M2;

               double t00 = A.m00*B.m00;

               MR.m00 += t00;
               break;
            }
            case 3: {
               Matrix1x3 A = (Matrix1x3)M1;
               Matrix1x3 B = (Matrix1x3)M2;

               MR.m00 += A.m00*B.m00 + A.m01*B.m01 + A.m02*B.m02;
               break;
            }
            case 6: {
               Matrix1x6 A = (Matrix1x6)M1;
               Matrix1x6 B = (Matrix1x6)M2;

               MR.m00 += (A.m00*B.m00 + A.m01*B.m01 + A.m02*B.m02 + A.m03*B.m03 +
                          A.m04*B.m04 + A.m05*B.m05);
               break;
            }
         }
      }
      else {
         for (int k=0; k<M1.colSize(); k++) {
            MR.m00 += M1.get(0,k)*M2.get(0,k);
         }
      }
   }

   public static void mulTransposeRightAdd1x3 (Matrix1x3 MR, Matrix M1, Matrix M2) {
      if (M1.rowSize() != 1 ||
          M2.rowSize() != 3 ||
          M1.colSize() != M2.colSize()) {
         throw new ImproperSizeException (
            "matrix sizes "+M1.getSize()+" and "+M2.getSize()+
            " do not conform to "+MR.getSize());
      }
      if (M1.isFixedSize() && M2.isFixedSize()) {
         switch (M1.colSize()) {
            case 1: {
               Matrix1x1 A = (Matrix1x1)M1;
               Matrix3x1 B = (Matrix3x1)M2;

               MR.m00 += A.m00*B.m00;
               MR.m01 += A.m00*B.m10;
               MR.m02 += A.m00*B.m20;
               break;
            }
            case 3: {
               Matrix1x3 A = (Matrix1x3)M1;
               Matrix3dBase B = (Matrix3dBase)M2;

               double t00 = A.m00*B.m00 + A.m01*B.m01 + A.m02*B.m02;
               double t01 = A.m00*B.m10 + A.m01*B.m11 + A.m02*B.m12;
               double t02 = A.m00*B.m20 + A.m01*B.m21 + A.m02*B.m22;

               MR.m00 += t00;
               MR.m01 += t01;
               MR.m02 += t02;
               break;
            }
            case 6: {
               Matrix1x6 A = (Matrix1x6)M1;
               Matrix3x6 B = (Matrix3x6)M2;

               MR.m00 += (A.m00*B.m00 + A.m01*B.m01 + A.m02*B.m02 + A.m03*B.m03 +
                          A.m04*B.m04 + A.m05*B.m05);
               MR.m01 += (A.m00*B.m10 + A.m01*B.m11 + A.m02*B.m12 + A.m03*B.m13 +
                          A.m04*B.m14 + A.m05*B.m15);
               MR.m02 += (A.m00*B.m20 + A.m01*B.m21 + A.m02*B.m22 + A.m03*B.m23 +
                          A.m04*B.m24 + A.m05*B.m25);
               break;
            }
         }
      }
      else {
         for (int k=0; k<M1.colSize(); k++) {
            MR.m00 += M1.get(0,k)*M2.get(0,k);
            MR.m01 += M1.get(0,k)*M2.get(1,k);
            MR.m02 += M1.get(0,k)*M2.get(2,k);
         }
      }
   }

   public static void mulTransposeRightAdd1x6 (Matrix1x6 MR, Matrix M1, Matrix M2) {
      if (M1.rowSize() != 1 ||
          M2.rowSize() != 6 ||
          M1.colSize() != M2.colSize()) {
         throw new ImproperSizeException (
            "matrix sizes "+M1.getSize()+" and "+M2.getSize()+
            " do not conform to "+MR.getSize());
      }
      if (M1.isFixedSize() && M2.isFixedSize()) {
         switch (M1.colSize()) {
            case 1: {
               Matrix1x1 A = (Matrix1x1)M1;
               Matrix6x1 B = (Matrix6x1)M2;

               MR.m00 += A.m00*B.m00;
               MR.m01 += A.m00*B.m10;
               MR.m02 += A.m00*B.m20;
               MR.m03 += A.m00*B.m30;
               MR.m04 += A.m00*B.m40;
               MR.m05 += A.m00*B.m50;
               break;
            }
            case 3: {
               Matrix1x3 A = (Matrix1x3)M1;
               Matrix6x3 B = (Matrix6x3)M2;

               MR.m00 += A.m00*B.m00 + A.m01*B.m01 + A.m02*B.m02;
               MR.m01 += A.m00*B.m10 + A.m01*B.m11 + A.m02*B.m12;
               MR.m02 += A.m00*B.m20 + A.m01*B.m21 + A.m02*B.m22;
               MR.m03 += A.m00*B.m30 + A.m01*B.m31 + A.m02*B.m32;
               MR.m04 += A.m00*B.m40 + A.m01*B.m41 + A.m02*B.m42;
               MR.m05 += A.m00*B.m50 + A.m01*B.m51 + A.m02*B.m52;
               break;
            }
            case 6: {
               Matrix1x6 A = (Matrix1x6)M1;
               Matrix6dBase B = (Matrix6dBase)M2;

               double t00 = (A.m00*B.m00 + A.m01*B.m01 + A.m02*B.m02 +
                             A.m03*B.m03 + A.m04*B.m04 + A.m05*B.m05);
               double t01 = (A.m00*B.m10 + A.m01*B.m11 + A.m02*B.m12 +
                             A.m03*B.m13 + A.m04*B.m14 + A.m05*B.m15);
               double t02 = (A.m00*B.m20 + A.m01*B.m21 + A.m02*B.m22 +
                             A.m03*B.m23 + A.m04*B.m24 + A.m05*B.m25);
               double t03 = (A.m00*B.m30 + A.m01*B.m31 + A.m02*B.m32 +
                             A.m03*B.m33 + A.m04*B.m34 + A.m05*B.m35);
               double t04 = (A.m00*B.m40 + A.m01*B.m41 + A.m02*B.m42 +
                             A.m03*B.m43 + A.m04*B.m44 + A.m05*B.m45);
               double t05 = (A.m00*B.m50 + A.m01*B.m51 + A.m02*B.m52 +
                             A.m03*B.m53 + A.m04*B.m54 + A.m05*B.m55);

               MR.m00 += t00;
               MR.m01 += t01;
               MR.m02 += t02;
               MR.m03 += t03;
               MR.m04 += t04;
               MR.m05 += t05;
               break;
            }
         }
      }
      else {
         for (int k=0; k<M1.colSize(); k++) {
            MR.m00 += M1.get(0,k)*M2.get(0,k);
            MR.m01 += M1.get(0,k)*M2.get(1,k);
            MR.m02 += M1.get(0,k)*M2.get(2,k);
            MR.m03 += M1.get(0,k)*M2.get(3,k);
            MR.m04 += M1.get(0,k)*M2.get(4,k);
            MR.m05 += M1.get(0,k)*M2.get(5,k);
         }
      }
   }

   public static void mulTransposeRightAdd2x2 (Matrix2dBase MR, Matrix M1, Matrix M2) {
      if (M1.rowSize() != 2 ||
          M2.rowSize() != 2 ||
          M1.colSize() != M2.colSize()) {
         throw new ImproperSizeException (
            "matrix sizes "+M1.getSize()+" and "+M2.getSize()+
            " do not conform to "+MR.getSize());
      }
      if (M1.isFixedSize() && M2.isFixedSize()) {
         switch (M1.colSize()) {
            case 2: {
               Matrix2dBase A = (Matrix2dBase)M1;
               Matrix2dBase B = (Matrix2dBase)M2;

               double t00 = A.m00*B.m00 + A.m01*B.m01;
               double t01 = A.m00*B.m10 + A.m01*B.m11;

               double t10 = A.m10*B.m00 + A.m11*B.m01;
               double t11 = A.m10*B.m10 + A.m11*B.m11;

               MR.m00 += t00;
               MR.m01 += t01;

               MR.m10 += t10;
               MR.m11 += t11;
               break;
            }
            case 3: {
               Matrix2x3 A = (Matrix2x3)M1;
               Matrix2x3 B = (Matrix2x3)M2;

               MR.m00 += A.m00*B.m00 + A.m01*B.m01 + A.m02*B.m02;
               MR.m01 += A.m00*B.m10 + A.m01*B.m11 + A.m02*B.m12;

               MR.m10 += A.m10*B.m00 + A.m11*B.m01 + A.m12*B.m02;
               MR.m11 += A.m10*B.m10 + A.m11*B.m11 + A.m12*B.m12;
               break;
            }
            case 6: {
               Matrix2x6 A = (Matrix2x6)M1;
               Matrix2x6 B = (Matrix2x6)M2;

               MR.m00 += (A.m00*B.m00 + A.m01*B.m01 + A.m02*B.m02 + A.m03*B.m03 +
                          A.m04*B.m04 + A.m05*B.m05);
               MR.m01 += (A.m00*B.m10 + A.m01*B.m11 + A.m02*B.m12 + A.m03*B.m13 +
                          A.m04*B.m14 + A.m05*B.m15);

               MR.m10 += (A.m10*B.m00 + A.m11*B.m01 + A.m12*B.m02 + A.m13*B.m03 +
                          A.m14*B.m04 + A.m15*B.m05);
               MR.m11 += (A.m10*B.m10 + A.m11*B.m11 + A.m12*B.m12 + A.m13*B.m13 +
                          A.m14*B.m14 + A.m15*B.m15);
               break;
            }
         }
      }
      else {
         for (int k=0; k<M1.colSize(); k++) {
            MR.m00 += M1.get(0,k)*M2.get(0,k);
            MR.m01 += M1.get(0,k)*M2.get(1,k);

            MR.m10 += M1.get(1,k)*M2.get(0,k);
            MR.m11 += M1.get(1,k)*M2.get(1,k);
         }
      }
   }

   public static void mulTransposeRightAdd2x3 (Matrix2x3 MR, Matrix M1, Matrix M2) {
      if (M1.rowSize() != 2 ||
          M2.rowSize() != 3 ||
          M1.colSize() != M2.colSize()) {
         throw new ImproperSizeException (
            "matrix sizes "+M1.getSize()+" and "+M2.getSize()+
            " do not conform to "+MR.getSize());
      }
      if (M1.isFixedSize() && M2.isFixedSize()) {
         switch (M1.colSize()) {
            case 2: {
               Matrix2dBase A = (Matrix2dBase)M1;
               Matrix3x2 B = (Matrix3x2)M2;

               MR.m00 += A.m00*B.m00 + A.m01*B.m01;
               MR.m01 += A.m00*B.m10 + A.m01*B.m11;
               MR.m02 += A.m00*B.m20 + A.m01*B.m21;

               MR.m10 += A.m10*B.m00 + A.m11*B.m01;
               MR.m11 += A.m10*B.m10 + A.m11*B.m11;
               MR.m12 += A.m10*B.m20 + A.m11*B.m21;
               break;
            }
            case 3: {
               Matrix2x3 A = (Matrix2x3)M1;
               Matrix3dBase B = (Matrix3dBase)M2;

               double t00 = A.m00*B.m00 + A.m01*B.m01 + A.m02*B.m02;
               double t01 = A.m00*B.m10 + A.m01*B.m11 + A.m02*B.m12;
               double t02 = A.m00*B.m20 + A.m01*B.m21 + A.m02*B.m22;

               double t10 = A.m10*B.m00 + A.m11*B.m01 + A.m12*B.m02;
               double t11 = A.m10*B.m10 + A.m11*B.m11 + A.m12*B.m12;
               double t12 = A.m10*B.m20 + A.m11*B.m21 + A.m12*B.m22;

               MR.m00 += t00;
               MR.m01 += t01;
               MR.m02 += t02;

               MR.m10 += t10;
               MR.m11 += t11;
               MR.m12 += t12;
               break;
            }
            case 6: {
               Matrix2x6 A = (Matrix2x6)M1;
               Matrix3x6 B = (Matrix3x6)M2;

               MR.m00 += (A.m00*B.m00 + A.m01*B.m01 + A.m02*B.m02 + A.m03*B.m03 +
                          A.m04*B.m04 + A.m05*B.m05);
               MR.m01 += (A.m00*B.m10 + A.m01*B.m11 + A.m02*B.m12 + A.m03*B.m13 +
                          A.m04*B.m14 + A.m05*B.m15);
               MR.m02 += (A.m00*B.m20 + A.m01*B.m21 + A.m02*B.m22 + A.m03*B.m23 +
                          A.m04*B.m24 + A.m05*B.m25);

               MR.m10 += (A.m10*B.m00 + A.m11*B.m01 + A.m12*B.m02 + A.m13*B.m03 +
                          A.m14*B.m04 + A.m15*B.m05);
               MR.m11 += (A.m10*B.m10 + A.m11*B.m11 + A.m12*B.m12 + A.m13*B.m13 +
                          A.m14*B.m14 + A.m15*B.m15);
               MR.m12 += (A.m10*B.m20 + A.m11*B.m21 + A.m12*B.m22 + A.m13*B.m23 +
                          A.m14*B.m24 + A.m15*B.m25);
               break;
            }
         }
      }
      else {
         for (int k=0; k<M1.colSize(); k++) {
            MR.m00 += M1.get(0,k)*M2.get(0,k);
            MR.m01 += M1.get(0,k)*M2.get(1,k);
            MR.m02 += M1.get(0,k)*M2.get(2,k);

            MR.m10 += M1.get(1,k)*M2.get(0,k);
            MR.m11 += M1.get(1,k)*M2.get(1,k);
            MR.m12 += M1.get(1,k)*M2.get(2,k);
         }
      }
   }

   public static void mulTransposeRightAdd2x6 (Matrix2x6 MR, Matrix M1, Matrix M2) {
      if (M1.rowSize() != 2 ||
          M2.rowSize() != 6 ||
          M1.colSize() != M2.colSize()) {
         throw new ImproperSizeException (
            "matrix sizes "+M1.getSize()+" and "+M2.getSize()+
            " do not conform to "+MR.getSize());
      }
      if (M1.isFixedSize() && M2.isFixedSize()) {
         switch (M1.colSize()) {
            case 2: {
               Matrix2dBase A = (Matrix2dBase)M1;
               Matrix6x2 B = (Matrix6x2)M2;

               MR.m00 += A.m00*B.m00 + A.m01*B.m01;
               MR.m01 += A.m00*B.m10 + A.m01*B.m11;
               MR.m02 += A.m00*B.m20 + A.m01*B.m21;
               MR.m03 += A.m00*B.m30 + A.m01*B.m31;
               MR.m04 += A.m00*B.m40 + A.m01*B.m41;
               MR.m05 += A.m00*B.m50 + A.m01*B.m51;

               MR.m10 += A.m10*B.m00 + A.m11*B.m01;
               MR.m11 += A.m10*B.m10 + A.m11*B.m11;
               MR.m12 += A.m10*B.m20 + A.m11*B.m21;
               MR.m13 += A.m10*B.m30 + A.m11*B.m31;
               MR.m14 += A.m10*B.m40 + A.m11*B.m41;
               MR.m15 += A.m10*B.m50 + A.m11*B.m51;
               break;
            }
            case 3: {
               Matrix2x3 A = (Matrix2x3)M1;
               Matrix6x3 B = (Matrix6x3)M2;

               MR.m00 += A.m00*B.m00 + A.m01*B.m01 + A.m02*B.m02;
               MR.m01 += A.m00*B.m10 + A.m01*B.m11 + A.m02*B.m12;
               MR.m02 += A.m00*B.m20 + A.m01*B.m21 + A.m02*B.m22;
               MR.m03 += A.m00*B.m30 + A.m01*B.m31 + A.m02*B.m32;
               MR.m04 += A.m00*B.m40 + A.m01*B.m41 + A.m02*B.m42;
               MR.m05 += A.m00*B.m50 + A.m01*B.m51 + A.m02*B.m52;

               MR.m10 += A.m10*B.m00 + A.m11*B.m01 + A.m12*B.m02;
               MR.m11 += A.m10*B.m10 + A.m11*B.m11 + A.m12*B.m12;
               MR.m12 += A.m10*B.m20 + A.m11*B.m21 + A.m12*B.m22;
               MR.m13 += A.m10*B.m30 + A.m11*B.m31 + A.m12*B.m32;
               MR.m14 += A.m10*B.m40 + A.m11*B.m41 + A.m12*B.m42;
               MR.m15 += A.m10*B.m50 + A.m11*B.m51 + A.m12*B.m52;
               break;
            }
            case 6: {
               Matrix2x6 A = (Matrix2x6)M1;
               Matrix6dBase B = (Matrix6dBase)M2;

               double t00 = (A.m00*B.m00 + A.m01*B.m01 + A.m02*B.m02 +
                             A.m03*B.m03 + A.m04*B.m04 + A.m05*B.m05);
               double t01 = (A.m00*B.m10 + A.m01*B.m11 + A.m02*B.m12 +
                             A.m03*B.m13 + A.m04*B.m14 + A.m05*B.m15);
               double t02 = (A.m00*B.m20 + A.m01*B.m21 + A.m02*B.m22 +
                             A.m03*B.m23 + A.m04*B.m24 + A.m05*B.m25);
               double t03 = (A.m00*B.m30 + A.m01*B.m31 + A.m02*B.m32 +
                             A.m03*B.m33 + A.m04*B.m34 + A.m05*B.m35);
               double t04 = (A.m00*B.m40 + A.m01*B.m41 + A.m02*B.m42 +
                             A.m03*B.m43 + A.m04*B.m44 + A.m05*B.m45);
               double t05 = (A.m00*B.m50 + A.m01*B.m51 + A.m02*B.m52 +
                             A.m03*B.m53 + A.m04*B.m54 + A.m05*B.m55);

               double t10 = (A.m10*B.m00 + A.m11*B.m01 + A.m12*B.m02 +
                             A.m13*B.m03 + A.m14*B.m04 + A.m15*B.m05);
               double t11 = (A.m10*B.m10 + A.m11*B.m11 + A.m12*B.m12 +
                             A.m13*B.m13 + A.m14*B.m14 + A.m15*B.m15);
               double t12 = (A.m10*B.m20 + A.m11*B.m21 + A.m12*B.m22 +
                             A.m13*B.m23 + A.m14*B.m24 + A.m15*B.m25);
               double t13 = (A.m10*B.m30 + A.m11*B.m31 + A.m12*B.m32 +
                             A.m13*B.m33 + A.m14*B.m34 + A.m15*B.m35);
               double t14 = (A.m10*B.m40 + A.m11*B.m41 + A.m12*B.m42 +
                             A.m13*B.m43 + A.m14*B.m44 + A.m15*B.m45);
               double t15 = (A.m10*B.m50 + A.m11*B.m51 + A.m12*B.m52 +
                             A.m13*B.m53 + A.m14*B.m54 + A.m15*B.m55);

               MR.m00 += t00;
               MR.m01 += t01;
               MR.m02 += t02;
               MR.m03 += t03;
               MR.m04 += t04;
               MR.m05 += t05;

               MR.m10 += t10;
               MR.m11 += t11;
               MR.m12 += t12;
               MR.m13 += t13;
               MR.m14 += t14;
               MR.m15 += t15;
               break;
            }
         }
      }
      else {
         for (int k=0; k<M1.colSize(); k++) {
            MR.m00 += M1.get(0,k)*M2.get(0,k);
            MR.m01 += M1.get(0,k)*M2.get(1,k);
            MR.m02 += M1.get(0,k)*M2.get(2,k);
            MR.m03 += M1.get(0,k)*M2.get(3,k);
            MR.m04 += M1.get(0,k)*M2.get(4,k);
            MR.m05 += M1.get(0,k)*M2.get(5,k);

            MR.m10 += M1.get(1,k)*M2.get(0,k);
            MR.m11 += M1.get(1,k)*M2.get(1,k);
            MR.m12 += M1.get(1,k)*M2.get(2,k);
            MR.m13 += M1.get(1,k)*M2.get(3,k);
            MR.m14 += M1.get(1,k)*M2.get(4,k);
            MR.m15 += M1.get(1,k)*M2.get(5,k);
         }
      }
   }

   public static void mulTransposeRightAdd3x1 (Matrix3x1 MR, Matrix M1, Matrix M2) {
      if (M1.rowSize() != 3 ||
          M2.rowSize() != 1 ||
          M1.colSize() != M2.colSize()) {
         throw new ImproperSizeException (
            "matrix sizes "+M1.getSize()+" and "+M2.getSize()+
            " do not conform to "+MR.getSize());
      }
      if (M1.isFixedSize() && M2.isFixedSize()) {
         switch (M1.colSize()) {
            case 1: {
               Matrix3x1 A = (Matrix3x1)M1;
               Matrix1x1 B = (Matrix1x1)M2;

               double t00 = A.m00*B.m00;

               double t10 = A.m10*B.m00;

               double t20 = A.m20*B.m00;

               MR.m00 += t00;

               MR.m10 += t10;

               MR.m20 += t20;
               break;
            }
            case 3: {
               Matrix3dBase A = (Matrix3dBase)M1;
               Matrix1x3 B = (Matrix1x3)M2;

               MR.m00 += A.m00*B.m00 + A.m01*B.m01 + A.m02*B.m02;

               MR.m10 += A.m10*B.m00 + A.m11*B.m01 + A.m12*B.m02;

               MR.m20 += A.m20*B.m00 + A.m21*B.m01 + A.m22*B.m02;
               break;
            }
            case 6: {
               Matrix3x6 A = (Matrix3x6)M1;
               Matrix1x6 B = (Matrix1x6)M2;

               MR.m00 += (A.m00*B.m00 + A.m01*B.m01 + A.m02*B.m02 + A.m03*B.m03 +
                          A.m04*B.m04 + A.m05*B.m05);

               MR.m10 += (A.m10*B.m00 + A.m11*B.m01 + A.m12*B.m02 + A.m13*B.m03 +
                          A.m14*B.m04 + A.m15*B.m05);

               MR.m20 += (A.m20*B.m00 + A.m21*B.m01 + A.m22*B.m02 + A.m23*B.m03 +
                          A.m24*B.m04 + A.m25*B.m05);
               break;
            }
         }
      }
      else {
         for (int k=0; k<M1.colSize(); k++) {
            MR.m00 += M1.get(0,k)*M2.get(0,k);

            MR.m10 += M1.get(1,k)*M2.get(0,k);

            MR.m20 += M1.get(2,k)*M2.get(0,k);
         }
      }
   }

   public static void mulTransposeRightAdd3x2 (Matrix3x2 MR, Matrix M1, Matrix M2) {
      if (M1.rowSize() != 3 ||
          M2.rowSize() != 2 ||
          M1.colSize() != M2.colSize()) {
         throw new ImproperSizeException (
            "matrix sizes "+M1.getSize()+" and "+M2.getSize()+
            " do not conform to "+MR.getSize());
      }
      if (M1.isFixedSize() && M2.isFixedSize()) {
         switch (M1.colSize()) {
            case 2: {
               Matrix3x2 A = (Matrix3x2)M1;
               Matrix2dBase B = (Matrix2dBase)M2;

               double t00 = A.m00*B.m00 + A.m01*B.m01;
               double t01 = A.m00*B.m10 + A.m01*B.m11;

               double t10 = A.m10*B.m00 + A.m11*B.m01;
               double t11 = A.m10*B.m10 + A.m11*B.m11;

               double t20 = A.m20*B.m00 + A.m21*B.m01;
               double t21 = A.m20*B.m10 + A.m21*B.m11;

               MR.m00 += t00;
               MR.m01 += t01;

               MR.m10 += t10;
               MR.m11 += t11;

               MR.m20 += t20;
               MR.m21 += t21;
               break;
            }
            case 3: {
               Matrix3dBase A = (Matrix3dBase)M1;
               Matrix2x3 B = (Matrix2x3)M2;

               MR.m00 += A.m00*B.m00 + A.m01*B.m01 + A.m02*B.m02;
               MR.m01 += A.m00*B.m10 + A.m01*B.m11 + A.m02*B.m12;

               MR.m10 += A.m10*B.m00 + A.m11*B.m01 + A.m12*B.m02;
               MR.m11 += A.m10*B.m10 + A.m11*B.m11 + A.m12*B.m12;

               MR.m20 += A.m20*B.m00 + A.m21*B.m01 + A.m22*B.m02;
               MR.m21 += A.m20*B.m10 + A.m21*B.m11 + A.m22*B.m12;
               break;
            }
            case 6: {
               Matrix3x6 A = (Matrix3x6)M1;
               Matrix2x6 B = (Matrix2x6)M2;

               MR.m00 += (A.m00*B.m00 + A.m01*B.m01 + A.m02*B.m02 + A.m03*B.m03 +
                          A.m04*B.m04 + A.m05*B.m05);
               MR.m01 += (A.m00*B.m10 + A.m01*B.m11 + A.m02*B.m12 + A.m03*B.m13 +
                          A.m04*B.m14 + A.m05*B.m15);

               MR.m10 += (A.m10*B.m00 + A.m11*B.m01 + A.m12*B.m02 + A.m13*B.m03 +
                          A.m14*B.m04 + A.m15*B.m05);
               MR.m11 += (A.m10*B.m10 + A.m11*B.m11 + A.m12*B.m12 + A.m13*B.m13 +
                          A.m14*B.m14 + A.m15*B.m15);

               MR.m20 += (A.m20*B.m00 + A.m21*B.m01 + A.m22*B.m02 + A.m23*B.m03 +
                          A.m24*B.m04 + A.m25*B.m05);
               MR.m21 += (A.m20*B.m10 + A.m21*B.m11 + A.m22*B.m12 + A.m23*B.m13 +
                          A.m24*B.m14 + A.m25*B.m15);
               break;
            }
         }
      }
      else {
         for (int k=0; k<M1.colSize(); k++) {
            MR.m00 += M1.get(0,k)*M2.get(0,k);
            MR.m01 += M1.get(0,k)*M2.get(1,k);

            MR.m10 += M1.get(1,k)*M2.get(0,k);
            MR.m11 += M1.get(1,k)*M2.get(1,k);

            MR.m20 += M1.get(2,k)*M2.get(0,k);
            MR.m21 += M1.get(2,k)*M2.get(1,k);
         }
      }
   }

   public static void mulTransposeRightAdd3x3 (Matrix3dBase MR, Matrix M1, Matrix M2) {
      if (M1.rowSize() != 3 ||
          M2.rowSize() != 3 ||
          M1.colSize() != M2.colSize()) {
         throw new ImproperSizeException (
            "matrix sizes "+M1.getSize()+" and "+M2.getSize()+
            " do not conform to "+MR.getSize());
      }
      if (M1.isFixedSize() && M2.isFixedSize()) {
         switch (M1.colSize()) {
            case 1: {
               Matrix3x1 A = (Matrix3x1)M1;
               Matrix3x1 B = (Matrix3x1)M2;

               MR.m00 += A.m00*B.m00;
               MR.m01 += A.m00*B.m10;
               MR.m02 += A.m00*B.m20;

               MR.m10 += A.m10*B.m00;
               MR.m11 += A.m10*B.m10;
               MR.m12 += A.m10*B.m20;

               MR.m20 += A.m20*B.m00;
               MR.m21 += A.m20*B.m10;
               MR.m22 += A.m20*B.m20;
               break;
            }
            case 2: {
               Matrix3x2 A = (Matrix3x2)M1;
               Matrix3x2 B = (Matrix3x2)M2;

               MR.m00 += A.m00*B.m00 + A.m01*B.m01;
               MR.m01 += A.m00*B.m10 + A.m01*B.m11;
               MR.m02 += A.m00*B.m20 + A.m01*B.m21;

               MR.m10 += A.m10*B.m00 + A.m11*B.m01;
               MR.m11 += A.m10*B.m10 + A.m11*B.m11;
               MR.m12 += A.m10*B.m20 + A.m11*B.m21;

               MR.m20 += A.m20*B.m00 + A.m21*B.m01;
               MR.m21 += A.m20*B.m10 + A.m21*B.m11;
               MR.m22 += A.m20*B.m20 + A.m21*B.m21;
               break;
            }
            case 3: {
               Matrix3dBase A = (Matrix3dBase)M1;
               Matrix3dBase B = (Matrix3dBase)M2;

               double t00 = A.m00*B.m00 + A.m01*B.m01 + A.m02*B.m02;
               double t01 = A.m00*B.m10 + A.m01*B.m11 + A.m02*B.m12;
               double t02 = A.m00*B.m20 + A.m01*B.m21 + A.m02*B.m22;

               double t10 = A.m10*B.m00 + A.m11*B.m01 + A.m12*B.m02;
               double t11 = A.m10*B.m10 + A.m11*B.m11 + A.m12*B.m12;
               double t12 = A.m10*B.m20 + A.m11*B.m21 + A.m12*B.m22;

               double t20 = A.m20*B.m00 + A.m21*B.m01 + A.m22*B.m02;
               double t21 = A.m20*B.m10 + A.m21*B.m11 + A.m22*B.m12;
               double t22 = A.m20*B.m20 + A.m21*B.m21 + A.m22*B.m22;

               MR.m00 += t00;
               MR.m01 += t01;
               MR.m02 += t02;

               MR.m10 += t10;
               MR.m11 += t11;
               MR.m12 += t12;

               MR.m20 += t20;
               MR.m21 += t21;
               MR.m22 += t22;
               break;
            }
            case 4: {
               Matrix3x4 A = (Matrix3x4)M1;
               Matrix3x4 B = (Matrix3x4)M2;

               MR.m00 += A.m00*B.m00 + A.m01*B.m01 + A.m02*B.m02 + A.m03*B.m03;
               MR.m01 += A.m00*B.m10 + A.m01*B.m11 + A.m02*B.m12 + A.m03*B.m13;
               MR.m02 += A.m00*B.m20 + A.m01*B.m21 + A.m02*B.m22 + A.m03*B.m23;

               MR.m10 += A.m10*B.m00 + A.m11*B.m01 + A.m12*B.m02 + A.m13*B.m03;
               MR.m11 += A.m10*B.m10 + A.m11*B.m11 + A.m12*B.m12 + A.m13*B.m13;
               MR.m12 += A.m10*B.m20 + A.m11*B.m21 + A.m12*B.m22 + A.m13*B.m23;

               MR.m20 += A.m20*B.m00 + A.m21*B.m01 + A.m22*B.m02 + A.m23*B.m03;
               MR.m21 += A.m20*B.m10 + A.m21*B.m11 + A.m22*B.m12 + A.m23*B.m13;
               MR.m22 += A.m20*B.m20 + A.m21*B.m21 + A.m22*B.m22 + A.m23*B.m23;
               break;
            }
            case 6: {
               Matrix3x6 A = (Matrix3x6)M1;
               Matrix3x6 B = (Matrix3x6)M2;

               MR.m00 += (A.m00*B.m00 + A.m01*B.m01 + A.m02*B.m02 + A.m03*B.m03 +
                          A.m04*B.m04 + A.m05*B.m05);
               MR.m01 += (A.m00*B.m10 + A.m01*B.m11 + A.m02*B.m12 + A.m03*B.m13 +
                          A.m04*B.m14 + A.m05*B.m15);
               MR.m02 += (A.m00*B.m20 + A.m01*B.m21 + A.m02*B.m22 + A.m03*B.m23 +
                          A.m04*B.m24 + A.m05*B.m25);

               MR.m10 += (A.m10*B.m00 + A.m11*B.m01 + A.m12*B.m02 + A.m13*B.m03 +
                          A.m14*B.m04 + A.m15*B.m05);
               MR.m11 += (A.m10*B.m10 + A.m11*B.m11 + A.m12*B.m12 + A.m13*B.m13 +
                          A.m14*B.m14 + A.m15*B.m15);
               MR.m12 += (A.m10*B.m20 + A.m11*B.m21 + A.m12*B.m22 + A.m13*B.m23 +
                          A.m14*B.m24 + A.m15*B.m25);

               MR.m20 += (A.m20*B.m00 + A.m21*B.m01 + A.m22*B.m02 + A.m23*B.m03 +
                          A.m24*B.m04 + A.m25*B.m05);
               MR.m21 += (A.m20*B.m10 + A.m21*B.m11 + A.m22*B.m12 + A.m23*B.m13 +
                          A.m24*B.m14 + A.m25*B.m15);
               MR.m22 += (A.m20*B.m20 + A.m21*B.m21 + A.m22*B.m22 + A.m23*B.m23 +
                          A.m24*B.m24 + A.m25*B.m25);
               break;
            }
         }
      }
      else {
         for (int k=0; k<M1.colSize(); k++) {
            MR.m00 += M1.get(0,k)*M2.get(0,k);
            MR.m01 += M1.get(0,k)*M2.get(1,k);
            MR.m02 += M1.get(0,k)*M2.get(2,k);

            MR.m10 += M1.get(1,k)*M2.get(0,k);
            MR.m11 += M1.get(1,k)*M2.get(1,k);
            MR.m12 += M1.get(1,k)*M2.get(2,k);

            MR.m20 += M1.get(2,k)*M2.get(0,k);
            MR.m21 += M1.get(2,k)*M2.get(1,k);
            MR.m22 += M1.get(2,k)*M2.get(2,k);
         }
      }
   }

   public static void mulTransposeRightAdd3x4 (Matrix3x4 MR, Matrix M1, Matrix M2) {
      if (M1.rowSize() != 3 ||
          M2.rowSize() != 4 ||
          M1.colSize() != M2.colSize()) {
         throw new ImproperSizeException (
            "matrix sizes "+M1.getSize()+" and "+M2.getSize()+
            " do not conform to "+MR.getSize());
      }
      if (M1.isFixedSize() && M2.isFixedSize()) {
         switch (M1.colSize()) {
            case 3: {
               Matrix3dBase A = (Matrix3dBase)M1;
               Matrix4x3 B = (Matrix4x3)M2;

               MR.m00 += A.m00*B.m00 + A.m01*B.m01 + A.m02*B.m02;
               MR.m01 += A.m00*B.m10 + A.m01*B.m11 + A.m02*B.m12;
               MR.m02 += A.m00*B.m20 + A.m01*B.m21 + A.m02*B.m22;
               MR.m03 += A.m00*B.m30 + A.m01*B.m31 + A.m02*B.m32;

               MR.m10 += A.m10*B.m00 + A.m11*B.m01 + A.m12*B.m02;
               MR.m11 += A.m10*B.m10 + A.m11*B.m11 + A.m12*B.m12;
               MR.m12 += A.m10*B.m20 + A.m11*B.m21 + A.m12*B.m22;
               MR.m13 += A.m10*B.m30 + A.m11*B.m31 + A.m12*B.m32;

               MR.m20 += A.m20*B.m00 + A.m21*B.m01 + A.m22*B.m02;
               MR.m21 += A.m20*B.m10 + A.m21*B.m11 + A.m22*B.m12;
               MR.m22 += A.m20*B.m20 + A.m21*B.m21 + A.m22*B.m22;
               MR.m23 += A.m20*B.m30 + A.m21*B.m31 + A.m22*B.m32;
               break;
            }
            case 4: {
               Matrix3x4 A = (Matrix3x4)M1;
               Matrix4dBase B = (Matrix4dBase)M2;

               double t00 = (A.m00*B.m00 + A.m01*B.m01 + A.m02*B.m02 +
                             A.m03*B.m03);
               double t01 = (A.m00*B.m10 + A.m01*B.m11 + A.m02*B.m12 +
                             A.m03*B.m13);
               double t02 = (A.m00*B.m20 + A.m01*B.m21 + A.m02*B.m22 +
                             A.m03*B.m23);
               double t03 = (A.m00*B.m30 + A.m01*B.m31 + A.m02*B.m32 +
                             A.m03*B.m33);

               double t10 = (A.m10*B.m00 + A.m11*B.m01 + A.m12*B.m02 +
                             A.m13*B.m03);
               double t11 = (A.m10*B.m10 + A.m11*B.m11 + A.m12*B.m12 +
                             A.m13*B.m13);
               double t12 = (A.m10*B.m20 + A.m11*B.m21 + A.m12*B.m22 +
                             A.m13*B.m23);
               double t13 = (A.m10*B.m30 + A.m11*B.m31 + A.m12*B.m32 +
                             A.m13*B.m33);

               double t20 = (A.m20*B.m00 + A.m21*B.m01 + A.m22*B.m02 +
                             A.m23*B.m03);
               double t21 = (A.m20*B.m10 + A.m21*B.m11 + A.m22*B.m12 +
                             A.m23*B.m13);
               double t22 = (A.m20*B.m20 + A.m21*B.m21 + A.m22*B.m22 +
                             A.m23*B.m23);
               double t23 = (A.m20*B.m30 + A.m21*B.m31 + A.m22*B.m32 +
                             A.m23*B.m33);

               MR.m00 += t00;
               MR.m01 += t01;
               MR.m02 += t02;
               MR.m03 += t03;

               MR.m10 += t10;
               MR.m11 += t11;
               MR.m12 += t12;
               MR.m13 += t13;

               MR.m20 += t20;
               MR.m21 += t21;
               MR.m22 += t22;
               MR.m23 += t23;
               break;
            }
         }
      }
      else {
         for (int k=0; k<M1.colSize(); k++) {
            MR.m00 += M1.get(0,k)*M2.get(0,k);
            MR.m01 += M1.get(0,k)*M2.get(1,k);
            MR.m02 += M1.get(0,k)*M2.get(2,k);
            MR.m03 += M1.get(0,k)*M2.get(3,k);

            MR.m10 += M1.get(1,k)*M2.get(0,k);
            MR.m11 += M1.get(1,k)*M2.get(1,k);
            MR.m12 += M1.get(1,k)*M2.get(2,k);
            MR.m13 += M1.get(1,k)*M2.get(3,k);

            MR.m20 += M1.get(2,k)*M2.get(0,k);
            MR.m21 += M1.get(2,k)*M2.get(1,k);
            MR.m22 += M1.get(2,k)*M2.get(2,k);
            MR.m23 += M1.get(2,k)*M2.get(3,k);
         }
      }
   }

   public static void mulTransposeRightAdd3x6 (Matrix3x6 MR, Matrix M1, Matrix M2) {
      if (M1.rowSize() != 3 ||
          M2.rowSize() != 6 ||
          M1.colSize() != M2.colSize()) {
         throw new ImproperSizeException (
            "matrix sizes "+M1.getSize()+" and "+M2.getSize()+
            " do not conform to "+MR.getSize());
      }
      if (M1.isFixedSize() && M2.isFixedSize()) {
         switch (M1.colSize()) {
            case 1: {
               Matrix3x1 A = (Matrix3x1)M1;
               Matrix6x1 B = (Matrix6x1)M2;

               MR.m00 += A.m00*B.m00;
               MR.m01 += A.m00*B.m10;
               MR.m02 += A.m00*B.m20;
               MR.m03 += A.m00*B.m30;
               MR.m04 += A.m00*B.m40;
               MR.m05 += A.m00*B.m50;

               MR.m10 += A.m10*B.m00;
               MR.m11 += A.m10*B.m10;
               MR.m12 += A.m10*B.m20;
               MR.m13 += A.m10*B.m30;
               MR.m14 += A.m10*B.m40;
               MR.m15 += A.m10*B.m50;

               MR.m20 += A.m20*B.m00;
               MR.m21 += A.m20*B.m10;
               MR.m22 += A.m20*B.m20;
               MR.m23 += A.m20*B.m30;
               MR.m24 += A.m20*B.m40;
               MR.m25 += A.m20*B.m50;
               break;
            }
            case 2: {
               Matrix3x2 A = (Matrix3x2)M1;
               Matrix6x2 B = (Matrix6x2)M2;

               MR.m00 += A.m00*B.m00 + A.m01*B.m01;
               MR.m01 += A.m00*B.m10 + A.m01*B.m11;
               MR.m02 += A.m00*B.m20 + A.m01*B.m21;
               MR.m03 += A.m00*B.m30 + A.m01*B.m31;
               MR.m04 += A.m00*B.m40 + A.m01*B.m41;
               MR.m05 += A.m00*B.m50 + A.m01*B.m51;

               MR.m10 += A.m10*B.m00 + A.m11*B.m01;
               MR.m11 += A.m10*B.m10 + A.m11*B.m11;
               MR.m12 += A.m10*B.m20 + A.m11*B.m21;
               MR.m13 += A.m10*B.m30 + A.m11*B.m31;
               MR.m14 += A.m10*B.m40 + A.m11*B.m41;
               MR.m15 += A.m10*B.m50 + A.m11*B.m51;

               MR.m20 += A.m20*B.m00 + A.m21*B.m01;
               MR.m21 += A.m20*B.m10 + A.m21*B.m11;
               MR.m22 += A.m20*B.m20 + A.m21*B.m21;
               MR.m23 += A.m20*B.m30 + A.m21*B.m31;
               MR.m24 += A.m20*B.m40 + A.m21*B.m41;
               MR.m25 += A.m20*B.m50 + A.m21*B.m51;
               break;
            }
            case 3: {
               Matrix3dBase A = (Matrix3dBase)M1;
               Matrix6x3 B = (Matrix6x3)M2;

               MR.m00 += A.m00*B.m00 + A.m01*B.m01 + A.m02*B.m02;
               MR.m01 += A.m00*B.m10 + A.m01*B.m11 + A.m02*B.m12;
               MR.m02 += A.m00*B.m20 + A.m01*B.m21 + A.m02*B.m22;
               MR.m03 += A.m00*B.m30 + A.m01*B.m31 + A.m02*B.m32;
               MR.m04 += A.m00*B.m40 + A.m01*B.m41 + A.m02*B.m42;
               MR.m05 += A.m00*B.m50 + A.m01*B.m51 + A.m02*B.m52;

               MR.m10 += A.m10*B.m00 + A.m11*B.m01 + A.m12*B.m02;
               MR.m11 += A.m10*B.m10 + A.m11*B.m11 + A.m12*B.m12;
               MR.m12 += A.m10*B.m20 + A.m11*B.m21 + A.m12*B.m22;
               MR.m13 += A.m10*B.m30 + A.m11*B.m31 + A.m12*B.m32;
               MR.m14 += A.m10*B.m40 + A.m11*B.m41 + A.m12*B.m42;
               MR.m15 += A.m10*B.m50 + A.m11*B.m51 + A.m12*B.m52;

               MR.m20 += A.m20*B.m00 + A.m21*B.m01 + A.m22*B.m02;
               MR.m21 += A.m20*B.m10 + A.m21*B.m11 + A.m22*B.m12;
               MR.m22 += A.m20*B.m20 + A.m21*B.m21 + A.m22*B.m22;
               MR.m23 += A.m20*B.m30 + A.m21*B.m31 + A.m22*B.m32;
               MR.m24 += A.m20*B.m40 + A.m21*B.m41 + A.m22*B.m42;
               MR.m25 += A.m20*B.m50 + A.m21*B.m51 + A.m22*B.m52;
               break;
            }
            case 6: {
               Matrix3x6 A = (Matrix3x6)M1;
               Matrix6dBase B = (Matrix6dBase)M2;

               double t00 = (A.m00*B.m00 + A.m01*B.m01 + A.m02*B.m02 +
                             A.m03*B.m03 + A.m04*B.m04 + A.m05*B.m05);
               double t01 = (A.m00*B.m10 + A.m01*B.m11 + A.m02*B.m12 +
                             A.m03*B.m13 + A.m04*B.m14 + A.m05*B.m15);
               double t02 = (A.m00*B.m20 + A.m01*B.m21 + A.m02*B.m22 +
                             A.m03*B.m23 + A.m04*B.m24 + A.m05*B.m25);
               double t03 = (A.m00*B.m30 + A.m01*B.m31 + A.m02*B.m32 +
                             A.m03*B.m33 + A.m04*B.m34 + A.m05*B.m35);
               double t04 = (A.m00*B.m40 + A.m01*B.m41 + A.m02*B.m42 +
                             A.m03*B.m43 + A.m04*B.m44 + A.m05*B.m45);
               double t05 = (A.m00*B.m50 + A.m01*B.m51 + A.m02*B.m52 +
                             A.m03*B.m53 + A.m04*B.m54 + A.m05*B.m55);

               double t10 = (A.m10*B.m00 + A.m11*B.m01 + A.m12*B.m02 +
                             A.m13*B.m03 + A.m14*B.m04 + A.m15*B.m05);
               double t11 = (A.m10*B.m10 + A.m11*B.m11 + A.m12*B.m12 +
                             A.m13*B.m13 + A.m14*B.m14 + A.m15*B.m15);
               double t12 = (A.m10*B.m20 + A.m11*B.m21 + A.m12*B.m22 +
                             A.m13*B.m23 + A.m14*B.m24 + A.m15*B.m25);
               double t13 = (A.m10*B.m30 + A.m11*B.m31 + A.m12*B.m32 +
                             A.m13*B.m33 + A.m14*B.m34 + A.m15*B.m35);
               double t14 = (A.m10*B.m40 + A.m11*B.m41 + A.m12*B.m42 +
                             A.m13*B.m43 + A.m14*B.m44 + A.m15*B.m45);
               double t15 = (A.m10*B.m50 + A.m11*B.m51 + A.m12*B.m52 +
                             A.m13*B.m53 + A.m14*B.m54 + A.m15*B.m55);

               double t20 = (A.m20*B.m00 + A.m21*B.m01 + A.m22*B.m02 +
                             A.m23*B.m03 + A.m24*B.m04 + A.m25*B.m05);
               double t21 = (A.m20*B.m10 + A.m21*B.m11 + A.m22*B.m12 +
                             A.m23*B.m13 + A.m24*B.m14 + A.m25*B.m15);
               double t22 = (A.m20*B.m20 + A.m21*B.m21 + A.m22*B.m22 +
                             A.m23*B.m23 + A.m24*B.m24 + A.m25*B.m25);
               double t23 = (A.m20*B.m30 + A.m21*B.m31 + A.m22*B.m32 +
                             A.m23*B.m33 + A.m24*B.m34 + A.m25*B.m35);
               double t24 = (A.m20*B.m40 + A.m21*B.m41 + A.m22*B.m42 +
                             A.m23*B.m43 + A.m24*B.m44 + A.m25*B.m45);
               double t25 = (A.m20*B.m50 + A.m21*B.m51 + A.m22*B.m52 +
                             A.m23*B.m53 + A.m24*B.m54 + A.m25*B.m55);

               MR.m00 += t00;
               MR.m01 += t01;
               MR.m02 += t02;
               MR.m03 += t03;
               MR.m04 += t04;
               MR.m05 += t05;

               MR.m10 += t10;
               MR.m11 += t11;
               MR.m12 += t12;
               MR.m13 += t13;
               MR.m14 += t14;
               MR.m15 += t15;

               MR.m20 += t20;
               MR.m21 += t21;
               MR.m22 += t22;
               MR.m23 += t23;
               MR.m24 += t24;
               MR.m25 += t25;
               break;
            }
         }
      }
      else {
         for (int k=0; k<M1.colSize(); k++) {
            MR.m00 += M1.get(0,k)*M2.get(0,k);
            MR.m01 += M1.get(0,k)*M2.get(1,k);
            MR.m02 += M1.get(0,k)*M2.get(2,k);
            MR.m03 += M1.get(0,k)*M2.get(3,k);
            MR.m04 += M1.get(0,k)*M2.get(4,k);
            MR.m05 += M1.get(0,k)*M2.get(5,k);

            MR.m10 += M1.get(1,k)*M2.get(0,k);
            MR.m11 += M1.get(1,k)*M2.get(1,k);
            MR.m12 += M1.get(1,k)*M2.get(2,k);
            MR.m13 += M1.get(1,k)*M2.get(3,k);
            MR.m14 += M1.get(1,k)*M2.get(4,k);
            MR.m15 += M1.get(1,k)*M2.get(5,k);

            MR.m20 += M1.get(2,k)*M2.get(0,k);
            MR.m21 += M1.get(2,k)*M2.get(1,k);
            MR.m22 += M1.get(2,k)*M2.get(2,k);
            MR.m23 += M1.get(2,k)*M2.get(3,k);
            MR.m24 += M1.get(2,k)*M2.get(4,k);
            MR.m25 += M1.get(2,k)*M2.get(5,k);
         }
      }
   }

   public static void mulTransposeRightAdd4x3 (Matrix4x3 MR, Matrix M1, Matrix M2) {
      if (M1.rowSize() != 4 ||
          M2.rowSize() != 3 ||
          M1.colSize() != M2.colSize()) {
         throw new ImproperSizeException (
            "matrix sizes "+M1.getSize()+" and "+M2.getSize()+
            " do not conform to "+MR.getSize());
      }
      if (M1.isFixedSize() && M2.isFixedSize()) {
         switch (M1.colSize()) {
            case 3: {
               Matrix4x3 A = (Matrix4x3)M1;
               Matrix3dBase B = (Matrix3dBase)M2;

               double t00 = A.m00*B.m00 + A.m01*B.m01 + A.m02*B.m02;
               double t01 = A.m00*B.m10 + A.m01*B.m11 + A.m02*B.m12;
               double t02 = A.m00*B.m20 + A.m01*B.m21 + A.m02*B.m22;

               double t10 = A.m10*B.m00 + A.m11*B.m01 + A.m12*B.m02;
               double t11 = A.m10*B.m10 + A.m11*B.m11 + A.m12*B.m12;
               double t12 = A.m10*B.m20 + A.m11*B.m21 + A.m12*B.m22;

               double t20 = A.m20*B.m00 + A.m21*B.m01 + A.m22*B.m02;
               double t21 = A.m20*B.m10 + A.m21*B.m11 + A.m22*B.m12;
               double t22 = A.m20*B.m20 + A.m21*B.m21 + A.m22*B.m22;

               double t30 = A.m30*B.m00 + A.m31*B.m01 + A.m32*B.m02;
               double t31 = A.m30*B.m10 + A.m31*B.m11 + A.m32*B.m12;
               double t32 = A.m30*B.m20 + A.m31*B.m21 + A.m32*B.m22;

               MR.m00 += t00;
               MR.m01 += t01;
               MR.m02 += t02;

               MR.m10 += t10;
               MR.m11 += t11;
               MR.m12 += t12;

               MR.m20 += t20;
               MR.m21 += t21;
               MR.m22 += t22;

               MR.m30 += t30;
               MR.m31 += t31;
               MR.m32 += t32;
               break;
            }
            case 4: {
               Matrix4dBase A = (Matrix4dBase)M1;
               Matrix3x4 B = (Matrix3x4)M2;

               MR.m00 += A.m00*B.m00 + A.m01*B.m01 + A.m02*B.m02 + A.m03*B.m03;
               MR.m01 += A.m00*B.m10 + A.m01*B.m11 + A.m02*B.m12 + A.m03*B.m13;
               MR.m02 += A.m00*B.m20 + A.m01*B.m21 + A.m02*B.m22 + A.m03*B.m23;

               MR.m10 += A.m10*B.m00 + A.m11*B.m01 + A.m12*B.m02 + A.m13*B.m03;
               MR.m11 += A.m10*B.m10 + A.m11*B.m11 + A.m12*B.m12 + A.m13*B.m13;
               MR.m12 += A.m10*B.m20 + A.m11*B.m21 + A.m12*B.m22 + A.m13*B.m23;

               MR.m20 += A.m20*B.m00 + A.m21*B.m01 + A.m22*B.m02 + A.m23*B.m03;
               MR.m21 += A.m20*B.m10 + A.m21*B.m11 + A.m22*B.m12 + A.m23*B.m13;
               MR.m22 += A.m20*B.m20 + A.m21*B.m21 + A.m22*B.m22 + A.m23*B.m23;

               MR.m30 += A.m30*B.m00 + A.m31*B.m01 + A.m32*B.m02 + A.m33*B.m03;
               MR.m31 += A.m30*B.m10 + A.m31*B.m11 + A.m32*B.m12 + A.m33*B.m13;
               MR.m32 += A.m30*B.m20 + A.m31*B.m21 + A.m32*B.m22 + A.m33*B.m23;
               break;
            }
         }
      }
      else {
         for (int k=0; k<M1.colSize(); k++) {
            MR.m00 += M1.get(0,k)*M2.get(0,k);
            MR.m01 += M1.get(0,k)*M2.get(1,k);
            MR.m02 += M1.get(0,k)*M2.get(2,k);

            MR.m10 += M1.get(1,k)*M2.get(0,k);
            MR.m11 += M1.get(1,k)*M2.get(1,k);
            MR.m12 += M1.get(1,k)*M2.get(2,k);

            MR.m20 += M1.get(2,k)*M2.get(0,k);
            MR.m21 += M1.get(2,k)*M2.get(1,k);
            MR.m22 += M1.get(2,k)*M2.get(2,k);

            MR.m30 += M1.get(3,k)*M2.get(0,k);
            MR.m31 += M1.get(3,k)*M2.get(1,k);
            MR.m32 += M1.get(3,k)*M2.get(2,k);
         }
      }
   }

   public static void mulTransposeRightAdd4x4 (Matrix4dBase MR, Matrix M1, Matrix M2) {
      if (M1.rowSize() != 4 ||
          M2.rowSize() != 4 ||
          M1.colSize() != M2.colSize()) {
         throw new ImproperSizeException (
            "matrix sizes "+M1.getSize()+" and "+M2.getSize()+
            " do not conform to "+MR.getSize());
      }
      if (M1.isFixedSize() && M2.isFixedSize()) {
         switch (M1.colSize()) {
            case 3: {
               Matrix4x3 A = (Matrix4x3)M1;
               Matrix4x3 B = (Matrix4x3)M2;

               MR.m00 += A.m00*B.m00 + A.m01*B.m01 + A.m02*B.m02;
               MR.m01 += A.m00*B.m10 + A.m01*B.m11 + A.m02*B.m12;
               MR.m02 += A.m00*B.m20 + A.m01*B.m21 + A.m02*B.m22;
               MR.m03 += A.m00*B.m30 + A.m01*B.m31 + A.m02*B.m32;

               MR.m10 += A.m10*B.m00 + A.m11*B.m01 + A.m12*B.m02;
               MR.m11 += A.m10*B.m10 + A.m11*B.m11 + A.m12*B.m12;
               MR.m12 += A.m10*B.m20 + A.m11*B.m21 + A.m12*B.m22;
               MR.m13 += A.m10*B.m30 + A.m11*B.m31 + A.m12*B.m32;

               MR.m20 += A.m20*B.m00 + A.m21*B.m01 + A.m22*B.m02;
               MR.m21 += A.m20*B.m10 + A.m21*B.m11 + A.m22*B.m12;
               MR.m22 += A.m20*B.m20 + A.m21*B.m21 + A.m22*B.m22;
               MR.m23 += A.m20*B.m30 + A.m21*B.m31 + A.m22*B.m32;

               MR.m30 += A.m30*B.m00 + A.m31*B.m01 + A.m32*B.m02;
               MR.m31 += A.m30*B.m10 + A.m31*B.m11 + A.m32*B.m12;
               MR.m32 += A.m30*B.m20 + A.m31*B.m21 + A.m32*B.m22;
               MR.m33 += A.m30*B.m30 + A.m31*B.m31 + A.m32*B.m32;
               break;
            }
            case 4: {
               Matrix4dBase A = (Matrix4dBase)M1;
               Matrix4dBase B = (Matrix4dBase)M2;

               double t00 = (A.m00*B.m00 + A.m01*B.m01 + A.m02*B.m02 +
                             A.m03*B.m03);
               double t01 = (A.m00*B.m10 + A.m01*B.m11 + A.m02*B.m12 +
                             A.m03*B.m13);
               double t02 = (A.m00*B.m20 + A.m01*B.m21 + A.m02*B.m22 +
                             A.m03*B.m23);
               double t03 = (A.m00*B.m30 + A.m01*B.m31 + A.m02*B.m32 +
                             A.m03*B.m33);

               double t10 = (A.m10*B.m00 + A.m11*B.m01 + A.m12*B.m02 +
                             A.m13*B.m03);
               double t11 = (A.m10*B.m10 + A.m11*B.m11 + A.m12*B.m12 +
                             A.m13*B.m13);
               double t12 = (A.m10*B.m20 + A.m11*B.m21 + A.m12*B.m22 +
                             A.m13*B.m23);
               double t13 = (A.m10*B.m30 + A.m11*B.m31 + A.m12*B.m32 +
                             A.m13*B.m33);

               double t20 = (A.m20*B.m00 + A.m21*B.m01 + A.m22*B.m02 +
                             A.m23*B.m03);
               double t21 = (A.m20*B.m10 + A.m21*B.m11 + A.m22*B.m12 +
                             A.m23*B.m13);
               double t22 = (A.m20*B.m20 + A.m21*B.m21 + A.m22*B.m22 +
                             A.m23*B.m23);
               double t23 = (A.m20*B.m30 + A.m21*B.m31 + A.m22*B.m32 +
                             A.m23*B.m33);

               double t30 = (A.m30*B.m00 + A.m31*B.m01 + A.m32*B.m02 +
                             A.m33*B.m03);
               double t31 = (A.m30*B.m10 + A.m31*B.m11 + A.m32*B.m12 +
                             A.m33*B.m13);
               double t32 = (A.m30*B.m20 + A.m31*B.m21 + A.m32*B.m22 +
                             A.m33*B.m23);
               double t33 = (A.m30*B.m30 + A.m31*B.m31 + A.m32*B.m32 +
                             A.m33*B.m33);

               MR.m00 += t00;
               MR.m01 += t01;
               MR.m02 += t02;
               MR.m03 += t03;

               MR.m10 += t10;
               MR.m11 += t11;
               MR.m12 += t12;
               MR.m13 += t13;

               MR.m20 += t20;
               MR.m21 += t21;
               MR.m22 += t22;
               MR.m23 += t23;

               MR.m30 += t30;
               MR.m31 += t31;
               MR.m32 += t32;
               MR.m33 += t33;
               break;
            }
         }
      }
      else {
         for (int k=0; k<M1.colSize(); k++) {
            MR.m00 += M1.get(0,k)*M2.get(0,k);
            MR.m01 += M1.get(0,k)*M2.get(1,k);
            MR.m02 += M1.get(0,k)*M2.get(2,k);
            MR.m03 += M1.get(0,k)*M2.get(3,k);

            MR.m10 += M1.get(1,k)*M2.get(0,k);
            MR.m11 += M1.get(1,k)*M2.get(1,k);
            MR.m12 += M1.get(1,k)*M2.get(2,k);
            MR.m13 += M1.get(1,k)*M2.get(3,k);

            MR.m20 += M1.get(2,k)*M2.get(0,k);
            MR.m21 += M1.get(2,k)*M2.get(1,k);
            MR.m22 += M1.get(2,k)*M2.get(2,k);
            MR.m23 += M1.get(2,k)*M2.get(3,k);

            MR.m30 += M1.get(3,k)*M2.get(0,k);
            MR.m31 += M1.get(3,k)*M2.get(1,k);
            MR.m32 += M1.get(3,k)*M2.get(2,k);
            MR.m33 += M1.get(3,k)*M2.get(3,k);
         }
      }
   }

   public static void mulTransposeRightAdd6x1 (Matrix6x1 MR, Matrix M1, Matrix M2) {
      if (M1.rowSize() != 6 ||
          M2.rowSize() != 1 ||
          M1.colSize() != M2.colSize()) {
         throw new ImproperSizeException (
            "matrix sizes "+M1.getSize()+" and "+M2.getSize()+
            " do not conform to "+MR.getSize());
      }
      if (M1.isFixedSize() && M2.isFixedSize()) {
         switch (M1.colSize()) {
            case 1: {
               Matrix6x1 A = (Matrix6x1)M1;
               Matrix1x1 B = (Matrix1x1)M2;

               double t00 = A.m00*B.m00;

               double t10 = A.m10*B.m00;

               double t20 = A.m20*B.m00;

               double t30 = A.m30*B.m00;

               double t40 = A.m40*B.m00;

               double t50 = A.m50*B.m00;

               MR.m00 += t00;

               MR.m10 += t10;

               MR.m20 += t20;

               MR.m30 += t30;

               MR.m40 += t40;

               MR.m50 += t50;
               break;
            }
            case 3: {
               Matrix6x3 A = (Matrix6x3)M1;
               Matrix1x3 B = (Matrix1x3)M2;

               MR.m00 += A.m00*B.m00 + A.m01*B.m01 + A.m02*B.m02;

               MR.m10 += A.m10*B.m00 + A.m11*B.m01 + A.m12*B.m02;

               MR.m20 += A.m20*B.m00 + A.m21*B.m01 + A.m22*B.m02;

               MR.m30 += A.m30*B.m00 + A.m31*B.m01 + A.m32*B.m02;

               MR.m40 += A.m40*B.m00 + A.m41*B.m01 + A.m42*B.m02;

               MR.m50 += A.m50*B.m00 + A.m51*B.m01 + A.m52*B.m02;
               break;
            }
            case 6: {
               Matrix6dBase A = (Matrix6dBase)M1;
               Matrix1x6 B = (Matrix1x6)M2;

               MR.m00 += (A.m00*B.m00 + A.m01*B.m01 + A.m02*B.m02 + A.m03*B.m03 +
                          A.m04*B.m04 + A.m05*B.m05);

               MR.m10 += (A.m10*B.m00 + A.m11*B.m01 + A.m12*B.m02 + A.m13*B.m03 +
                          A.m14*B.m04 + A.m15*B.m05);

               MR.m20 += (A.m20*B.m00 + A.m21*B.m01 + A.m22*B.m02 + A.m23*B.m03 +
                          A.m24*B.m04 + A.m25*B.m05);

               MR.m30 += (A.m30*B.m00 + A.m31*B.m01 + A.m32*B.m02 + A.m33*B.m03 +
                          A.m34*B.m04 + A.m35*B.m05);

               MR.m40 += (A.m40*B.m00 + A.m41*B.m01 + A.m42*B.m02 + A.m43*B.m03 +
                          A.m44*B.m04 + A.m45*B.m05);

               MR.m50 += (A.m50*B.m00 + A.m51*B.m01 + A.m52*B.m02 + A.m53*B.m03 +
                          A.m54*B.m04 + A.m55*B.m05);
               break;
            }
         }
      }
      else {
         for (int k=0; k<M1.colSize(); k++) {
            MR.m00 += M1.get(0,k)*M2.get(0,k);

            MR.m10 += M1.get(1,k)*M2.get(0,k);

            MR.m20 += M1.get(2,k)*M2.get(0,k);

            MR.m30 += M1.get(3,k)*M2.get(0,k);

            MR.m40 += M1.get(4,k)*M2.get(0,k);

            MR.m50 += M1.get(5,k)*M2.get(0,k);
         }
      }
   }

   public static void mulTransposeRightAdd6x2 (Matrix6x2 MR, Matrix M1, Matrix M2) {
      if (M1.rowSize() != 6 ||
          M2.rowSize() != 2 ||
          M1.colSize() != M2.colSize()) {
         throw new ImproperSizeException (
            "matrix sizes "+M1.getSize()+" and "+M2.getSize()+
            " do not conform to "+MR.getSize());
      }
      if (M1.isFixedSize() && M2.isFixedSize()) {
         switch (M1.colSize()) {
            case 2: {
               Matrix6x2 A = (Matrix6x2)M1;
               Matrix2dBase B = (Matrix2dBase)M2;

               double t00 = A.m00*B.m00 + A.m01*B.m01;
               double t01 = A.m00*B.m10 + A.m01*B.m11;

               double t10 = A.m10*B.m00 + A.m11*B.m01;
               double t11 = A.m10*B.m10 + A.m11*B.m11;

               double t20 = A.m20*B.m00 + A.m21*B.m01;
               double t21 = A.m20*B.m10 + A.m21*B.m11;

               double t30 = A.m30*B.m00 + A.m31*B.m01;
               double t31 = A.m30*B.m10 + A.m31*B.m11;

               double t40 = A.m40*B.m00 + A.m41*B.m01;
               double t41 = A.m40*B.m10 + A.m41*B.m11;

               double t50 = A.m50*B.m00 + A.m51*B.m01;
               double t51 = A.m50*B.m10 + A.m51*B.m11;

               MR.m00 += t00;
               MR.m01 += t01;

               MR.m10 += t10;
               MR.m11 += t11;

               MR.m20 += t20;
               MR.m21 += t21;

               MR.m30 += t30;
               MR.m31 += t31;

               MR.m40 += t40;
               MR.m41 += t41;

               MR.m50 += t50;
               MR.m51 += t51;
               break;
            }
            case 3: {
               Matrix6x3 A = (Matrix6x3)M1;
               Matrix2x3 B = (Matrix2x3)M2;

               MR.m00 += A.m00*B.m00 + A.m01*B.m01 + A.m02*B.m02;
               MR.m01 += A.m00*B.m10 + A.m01*B.m11 + A.m02*B.m12;

               MR.m10 += A.m10*B.m00 + A.m11*B.m01 + A.m12*B.m02;
               MR.m11 += A.m10*B.m10 + A.m11*B.m11 + A.m12*B.m12;

               MR.m20 += A.m20*B.m00 + A.m21*B.m01 + A.m22*B.m02;
               MR.m21 += A.m20*B.m10 + A.m21*B.m11 + A.m22*B.m12;

               MR.m30 += A.m30*B.m00 + A.m31*B.m01 + A.m32*B.m02;
               MR.m31 += A.m30*B.m10 + A.m31*B.m11 + A.m32*B.m12;

               MR.m40 += A.m40*B.m00 + A.m41*B.m01 + A.m42*B.m02;
               MR.m41 += A.m40*B.m10 + A.m41*B.m11 + A.m42*B.m12;

               MR.m50 += A.m50*B.m00 + A.m51*B.m01 + A.m52*B.m02;
               MR.m51 += A.m50*B.m10 + A.m51*B.m11 + A.m52*B.m12;
               break;
            }
            case 6: {
               Matrix6dBase A = (Matrix6dBase)M1;
               Matrix2x6 B = (Matrix2x6)M2;

               MR.m00 += (A.m00*B.m00 + A.m01*B.m01 + A.m02*B.m02 + A.m03*B.m03 +
                          A.m04*B.m04 + A.m05*B.m05);
               MR.m01 += (A.m00*B.m10 + A.m01*B.m11 + A.m02*B.m12 + A.m03*B.m13 +
                          A.m04*B.m14 + A.m05*B.m15);

               MR.m10 += (A.m10*B.m00 + A.m11*B.m01 + A.m12*B.m02 + A.m13*B.m03 +
                          A.m14*B.m04 + A.m15*B.m05);
               MR.m11 += (A.m10*B.m10 + A.m11*B.m11 + A.m12*B.m12 + A.m13*B.m13 +
                          A.m14*B.m14 + A.m15*B.m15);

               MR.m20 += (A.m20*B.m00 + A.m21*B.m01 + A.m22*B.m02 + A.m23*B.m03 +
                          A.m24*B.m04 + A.m25*B.m05);
               MR.m21 += (A.m20*B.m10 + A.m21*B.m11 + A.m22*B.m12 + A.m23*B.m13 +
                          A.m24*B.m14 + A.m25*B.m15);

               MR.m30 += (A.m30*B.m00 + A.m31*B.m01 + A.m32*B.m02 + A.m33*B.m03 +
                          A.m34*B.m04 + A.m35*B.m05);
               MR.m31 += (A.m30*B.m10 + A.m31*B.m11 + A.m32*B.m12 + A.m33*B.m13 +
                          A.m34*B.m14 + A.m35*B.m15);

               MR.m40 += (A.m40*B.m00 + A.m41*B.m01 + A.m42*B.m02 + A.m43*B.m03 +
                          A.m44*B.m04 + A.m45*B.m05);
               MR.m41 += (A.m40*B.m10 + A.m41*B.m11 + A.m42*B.m12 + A.m43*B.m13 +
                          A.m44*B.m14 + A.m45*B.m15);

               MR.m50 += (A.m50*B.m00 + A.m51*B.m01 + A.m52*B.m02 + A.m53*B.m03 +
                          A.m54*B.m04 + A.m55*B.m05);
               MR.m51 += (A.m50*B.m10 + A.m51*B.m11 + A.m52*B.m12 + A.m53*B.m13 +
                          A.m54*B.m14 + A.m55*B.m15);
               break;
            }
         }
      }
      else {
         for (int k=0; k<M1.colSize(); k++) {
            MR.m00 += M1.get(0,k)*M2.get(0,k);
            MR.m01 += M1.get(0,k)*M2.get(1,k);

            MR.m10 += M1.get(1,k)*M2.get(0,k);
            MR.m11 += M1.get(1,k)*M2.get(1,k);

            MR.m20 += M1.get(2,k)*M2.get(0,k);
            MR.m21 += M1.get(2,k)*M2.get(1,k);

            MR.m30 += M1.get(3,k)*M2.get(0,k);
            MR.m31 += M1.get(3,k)*M2.get(1,k);

            MR.m40 += M1.get(4,k)*M2.get(0,k);
            MR.m41 += M1.get(4,k)*M2.get(1,k);

            MR.m50 += M1.get(5,k)*M2.get(0,k);
            MR.m51 += M1.get(5,k)*M2.get(1,k);
         }
      }
   }

   public static void mulTransposeRightAdd6x3 (Matrix6x3 MR, Matrix M1, Matrix M2) {
      if (M1.rowSize() != 6 ||
          M2.rowSize() != 3 ||
          M1.colSize() != M2.colSize()) {
         throw new ImproperSizeException (
            "matrix sizes "+M1.getSize()+" and "+M2.getSize()+
            " do not conform to "+MR.getSize());
      }
      if (M1.isFixedSize() && M2.isFixedSize()) {
         switch (M1.colSize()) {
            case 1: {
               Matrix6x1 A = (Matrix6x1)M1;
               Matrix3x1 B = (Matrix3x1)M2;

               MR.m00 += A.m00*B.m00;
               MR.m01 += A.m00*B.m10;
               MR.m02 += A.m00*B.m20;

               MR.m10 += A.m10*B.m00;
               MR.m11 += A.m10*B.m10;
               MR.m12 += A.m10*B.m20;

               MR.m20 += A.m20*B.m00;
               MR.m21 += A.m20*B.m10;
               MR.m22 += A.m20*B.m20;

               MR.m30 += A.m30*B.m00;
               MR.m31 += A.m30*B.m10;
               MR.m32 += A.m30*B.m20;

               MR.m40 += A.m40*B.m00;
               MR.m41 += A.m40*B.m10;
               MR.m42 += A.m40*B.m20;

               MR.m50 += A.m50*B.m00;
               MR.m51 += A.m50*B.m10;
               MR.m52 += A.m50*B.m20;
               break;
            }
            case 2: {
               Matrix6x2 A = (Matrix6x2)M1;
               Matrix3x2 B = (Matrix3x2)M2;

               MR.m00 += A.m00*B.m00 + A.m01*B.m01;
               MR.m01 += A.m00*B.m10 + A.m01*B.m11;
               MR.m02 += A.m00*B.m20 + A.m01*B.m21;

               MR.m10 += A.m10*B.m00 + A.m11*B.m01;
               MR.m11 += A.m10*B.m10 + A.m11*B.m11;
               MR.m12 += A.m10*B.m20 + A.m11*B.m21;

               MR.m20 += A.m20*B.m00 + A.m21*B.m01;
               MR.m21 += A.m20*B.m10 + A.m21*B.m11;
               MR.m22 += A.m20*B.m20 + A.m21*B.m21;

               MR.m30 += A.m30*B.m00 + A.m31*B.m01;
               MR.m31 += A.m30*B.m10 + A.m31*B.m11;
               MR.m32 += A.m30*B.m20 + A.m31*B.m21;

               MR.m40 += A.m40*B.m00 + A.m41*B.m01;
               MR.m41 += A.m40*B.m10 + A.m41*B.m11;
               MR.m42 += A.m40*B.m20 + A.m41*B.m21;

               MR.m50 += A.m50*B.m00 + A.m51*B.m01;
               MR.m51 += A.m50*B.m10 + A.m51*B.m11;
               MR.m52 += A.m50*B.m20 + A.m51*B.m21;
               break;
            }
            case 3: {
               Matrix6x3 A = (Matrix6x3)M1;
               Matrix3dBase B = (Matrix3dBase)M2;

               double t00 = A.m00*B.m00 + A.m01*B.m01 + A.m02*B.m02;
               double t01 = A.m00*B.m10 + A.m01*B.m11 + A.m02*B.m12;
               double t02 = A.m00*B.m20 + A.m01*B.m21 + A.m02*B.m22;

               double t10 = A.m10*B.m00 + A.m11*B.m01 + A.m12*B.m02;
               double t11 = A.m10*B.m10 + A.m11*B.m11 + A.m12*B.m12;
               double t12 = A.m10*B.m20 + A.m11*B.m21 + A.m12*B.m22;

               double t20 = A.m20*B.m00 + A.m21*B.m01 + A.m22*B.m02;
               double t21 = A.m20*B.m10 + A.m21*B.m11 + A.m22*B.m12;
               double t22 = A.m20*B.m20 + A.m21*B.m21 + A.m22*B.m22;

               double t30 = A.m30*B.m00 + A.m31*B.m01 + A.m32*B.m02;
               double t31 = A.m30*B.m10 + A.m31*B.m11 + A.m32*B.m12;
               double t32 = A.m30*B.m20 + A.m31*B.m21 + A.m32*B.m22;

               double t40 = A.m40*B.m00 + A.m41*B.m01 + A.m42*B.m02;
               double t41 = A.m40*B.m10 + A.m41*B.m11 + A.m42*B.m12;
               double t42 = A.m40*B.m20 + A.m41*B.m21 + A.m42*B.m22;

               double t50 = A.m50*B.m00 + A.m51*B.m01 + A.m52*B.m02;
               double t51 = A.m50*B.m10 + A.m51*B.m11 + A.m52*B.m12;
               double t52 = A.m50*B.m20 + A.m51*B.m21 + A.m52*B.m22;

               MR.m00 += t00;
               MR.m01 += t01;
               MR.m02 += t02;

               MR.m10 += t10;
               MR.m11 += t11;
               MR.m12 += t12;

               MR.m20 += t20;
               MR.m21 += t21;
               MR.m22 += t22;

               MR.m30 += t30;
               MR.m31 += t31;
               MR.m32 += t32;

               MR.m40 += t40;
               MR.m41 += t41;
               MR.m42 += t42;

               MR.m50 += t50;
               MR.m51 += t51;
               MR.m52 += t52;
               break;
            }
            case 6: {
               Matrix6dBase A = (Matrix6dBase)M1;
               Matrix3x6 B = (Matrix3x6)M2;

               MR.m00 += (A.m00*B.m00 + A.m01*B.m01 + A.m02*B.m02 + A.m03*B.m03 +
                          A.m04*B.m04 + A.m05*B.m05);
               MR.m01 += (A.m00*B.m10 + A.m01*B.m11 + A.m02*B.m12 + A.m03*B.m13 +
                          A.m04*B.m14 + A.m05*B.m15);
               MR.m02 += (A.m00*B.m20 + A.m01*B.m21 + A.m02*B.m22 + A.m03*B.m23 +
                          A.m04*B.m24 + A.m05*B.m25);

               MR.m10 += (A.m10*B.m00 + A.m11*B.m01 + A.m12*B.m02 + A.m13*B.m03 +
                          A.m14*B.m04 + A.m15*B.m05);
               MR.m11 += (A.m10*B.m10 + A.m11*B.m11 + A.m12*B.m12 + A.m13*B.m13 +
                          A.m14*B.m14 + A.m15*B.m15);
               MR.m12 += (A.m10*B.m20 + A.m11*B.m21 + A.m12*B.m22 + A.m13*B.m23 +
                          A.m14*B.m24 + A.m15*B.m25);

               MR.m20 += (A.m20*B.m00 + A.m21*B.m01 + A.m22*B.m02 + A.m23*B.m03 +
                          A.m24*B.m04 + A.m25*B.m05);
               MR.m21 += (A.m20*B.m10 + A.m21*B.m11 + A.m22*B.m12 + A.m23*B.m13 +
                          A.m24*B.m14 + A.m25*B.m15);
               MR.m22 += (A.m20*B.m20 + A.m21*B.m21 + A.m22*B.m22 + A.m23*B.m23 +
                          A.m24*B.m24 + A.m25*B.m25);

               MR.m30 += (A.m30*B.m00 + A.m31*B.m01 + A.m32*B.m02 + A.m33*B.m03 +
                          A.m34*B.m04 + A.m35*B.m05);
               MR.m31 += (A.m30*B.m10 + A.m31*B.m11 + A.m32*B.m12 + A.m33*B.m13 +
                          A.m34*B.m14 + A.m35*B.m15);
               MR.m32 += (A.m30*B.m20 + A.m31*B.m21 + A.m32*B.m22 + A.m33*B.m23 +
                          A.m34*B.m24 + A.m35*B.m25);

               MR.m40 += (A.m40*B.m00 + A.m41*B.m01 + A.m42*B.m02 + A.m43*B.m03 +
                          A.m44*B.m04 + A.m45*B.m05);
               MR.m41 += (A.m40*B.m10 + A.m41*B.m11 + A.m42*B.m12 + A.m43*B.m13 +
                          A.m44*B.m14 + A.m45*B.m15);
               MR.m42 += (A.m40*B.m20 + A.m41*B.m21 + A.m42*B.m22 + A.m43*B.m23 +
                          A.m44*B.m24 + A.m45*B.m25);

               MR.m50 += (A.m50*B.m00 + A.m51*B.m01 + A.m52*B.m02 + A.m53*B.m03 +
                          A.m54*B.m04 + A.m55*B.m05);
               MR.m51 += (A.m50*B.m10 + A.m51*B.m11 + A.m52*B.m12 + A.m53*B.m13 +
                          A.m54*B.m14 + A.m55*B.m15);
               MR.m52 += (A.m50*B.m20 + A.m51*B.m21 + A.m52*B.m22 + A.m53*B.m23 +
                          A.m54*B.m24 + A.m55*B.m25);
               break;
            }
         }
      }
      else {
         for (int k=0; k<M1.colSize(); k++) {
            MR.m00 += M1.get(0,k)*M2.get(0,k);
            MR.m01 += M1.get(0,k)*M2.get(1,k);
            MR.m02 += M1.get(0,k)*M2.get(2,k);

            MR.m10 += M1.get(1,k)*M2.get(0,k);
            MR.m11 += M1.get(1,k)*M2.get(1,k);
            MR.m12 += M1.get(1,k)*M2.get(2,k);

            MR.m20 += M1.get(2,k)*M2.get(0,k);
            MR.m21 += M1.get(2,k)*M2.get(1,k);
            MR.m22 += M1.get(2,k)*M2.get(2,k);

            MR.m30 += M1.get(3,k)*M2.get(0,k);
            MR.m31 += M1.get(3,k)*M2.get(1,k);
            MR.m32 += M1.get(3,k)*M2.get(2,k);

            MR.m40 += M1.get(4,k)*M2.get(0,k);
            MR.m41 += M1.get(4,k)*M2.get(1,k);
            MR.m42 += M1.get(4,k)*M2.get(2,k);

            MR.m50 += M1.get(5,k)*M2.get(0,k);
            MR.m51 += M1.get(5,k)*M2.get(1,k);
            MR.m52 += M1.get(5,k)*M2.get(2,k);
         }
      }
   }

   public static void mulTransposeRightAdd6x6 (Matrix6dBase MR, Matrix M1, Matrix M2) {
      if (M1.rowSize() != 6 ||
          M2.rowSize() != 6 ||
          M1.colSize() != M2.colSize()) {
         throw new ImproperSizeException (
            "matrix sizes "+M1.getSize()+" and "+M2.getSize()+
            " do not conform to "+MR.getSize());
      }
      if (M1.isFixedSize() && M2.isFixedSize()) {
         switch (M1.colSize()) {
            case 1: {
               Matrix6x1 A = (Matrix6x1)M1;
               Matrix6x1 B = (Matrix6x1)M2;

               MR.m00 += A.m00*B.m00;
               MR.m01 += A.m00*B.m10;
               MR.m02 += A.m00*B.m20;
               MR.m03 += A.m00*B.m30;
               MR.m04 += A.m00*B.m40;
               MR.m05 += A.m00*B.m50;

               MR.m10 += A.m10*B.m00;
               MR.m11 += A.m10*B.m10;
               MR.m12 += A.m10*B.m20;
               MR.m13 += A.m10*B.m30;
               MR.m14 += A.m10*B.m40;
               MR.m15 += A.m10*B.m50;

               MR.m20 += A.m20*B.m00;
               MR.m21 += A.m20*B.m10;
               MR.m22 += A.m20*B.m20;
               MR.m23 += A.m20*B.m30;
               MR.m24 += A.m20*B.m40;
               MR.m25 += A.m20*B.m50;

               MR.m30 += A.m30*B.m00;
               MR.m31 += A.m30*B.m10;
               MR.m32 += A.m30*B.m20;
               MR.m33 += A.m30*B.m30;
               MR.m34 += A.m30*B.m40;
               MR.m35 += A.m30*B.m50;

               MR.m40 += A.m40*B.m00;
               MR.m41 += A.m40*B.m10;
               MR.m42 += A.m40*B.m20;
               MR.m43 += A.m40*B.m30;
               MR.m44 += A.m40*B.m40;
               MR.m45 += A.m40*B.m50;

               MR.m50 += A.m50*B.m00;
               MR.m51 += A.m50*B.m10;
               MR.m52 += A.m50*B.m20;
               MR.m53 += A.m50*B.m30;
               MR.m54 += A.m50*B.m40;
               MR.m55 += A.m50*B.m50;
               break;
            }
            case 2: {
               Matrix6x2 A = (Matrix6x2)M1;
               Matrix6x2 B = (Matrix6x2)M2;

               MR.m00 += A.m00*B.m00 + A.m01*B.m01;
               MR.m01 += A.m00*B.m10 + A.m01*B.m11;
               MR.m02 += A.m00*B.m20 + A.m01*B.m21;
               MR.m03 += A.m00*B.m30 + A.m01*B.m31;
               MR.m04 += A.m00*B.m40 + A.m01*B.m41;
               MR.m05 += A.m00*B.m50 + A.m01*B.m51;

               MR.m10 += A.m10*B.m00 + A.m11*B.m01;
               MR.m11 += A.m10*B.m10 + A.m11*B.m11;
               MR.m12 += A.m10*B.m20 + A.m11*B.m21;
               MR.m13 += A.m10*B.m30 + A.m11*B.m31;
               MR.m14 += A.m10*B.m40 + A.m11*B.m41;
               MR.m15 += A.m10*B.m50 + A.m11*B.m51;

               MR.m20 += A.m20*B.m00 + A.m21*B.m01;
               MR.m21 += A.m20*B.m10 + A.m21*B.m11;
               MR.m22 += A.m20*B.m20 + A.m21*B.m21;
               MR.m23 += A.m20*B.m30 + A.m21*B.m31;
               MR.m24 += A.m20*B.m40 + A.m21*B.m41;
               MR.m25 += A.m20*B.m50 + A.m21*B.m51;

               MR.m30 += A.m30*B.m00 + A.m31*B.m01;
               MR.m31 += A.m30*B.m10 + A.m31*B.m11;
               MR.m32 += A.m30*B.m20 + A.m31*B.m21;
               MR.m33 += A.m30*B.m30 + A.m31*B.m31;
               MR.m34 += A.m30*B.m40 + A.m31*B.m41;
               MR.m35 += A.m30*B.m50 + A.m31*B.m51;

               MR.m40 += A.m40*B.m00 + A.m41*B.m01;
               MR.m41 += A.m40*B.m10 + A.m41*B.m11;
               MR.m42 += A.m40*B.m20 + A.m41*B.m21;
               MR.m43 += A.m40*B.m30 + A.m41*B.m31;
               MR.m44 += A.m40*B.m40 + A.m41*B.m41;
               MR.m45 += A.m40*B.m50 + A.m41*B.m51;

               MR.m50 += A.m50*B.m00 + A.m51*B.m01;
               MR.m51 += A.m50*B.m10 + A.m51*B.m11;
               MR.m52 += A.m50*B.m20 + A.m51*B.m21;
               MR.m53 += A.m50*B.m30 + A.m51*B.m31;
               MR.m54 += A.m50*B.m40 + A.m51*B.m41;
               MR.m55 += A.m50*B.m50 + A.m51*B.m51;
               break;
            }
            case 3: {
               Matrix6x3 A = (Matrix6x3)M1;
               Matrix6x3 B = (Matrix6x3)M2;

               MR.m00 += A.m00*B.m00 + A.m01*B.m01 + A.m02*B.m02;
               MR.m01 += A.m00*B.m10 + A.m01*B.m11 + A.m02*B.m12;
               MR.m02 += A.m00*B.m20 + A.m01*B.m21 + A.m02*B.m22;
               MR.m03 += A.m00*B.m30 + A.m01*B.m31 + A.m02*B.m32;
               MR.m04 += A.m00*B.m40 + A.m01*B.m41 + A.m02*B.m42;
               MR.m05 += A.m00*B.m50 + A.m01*B.m51 + A.m02*B.m52;

               MR.m10 += A.m10*B.m00 + A.m11*B.m01 + A.m12*B.m02;
               MR.m11 += A.m10*B.m10 + A.m11*B.m11 + A.m12*B.m12;
               MR.m12 += A.m10*B.m20 + A.m11*B.m21 + A.m12*B.m22;
               MR.m13 += A.m10*B.m30 + A.m11*B.m31 + A.m12*B.m32;
               MR.m14 += A.m10*B.m40 + A.m11*B.m41 + A.m12*B.m42;
               MR.m15 += A.m10*B.m50 + A.m11*B.m51 + A.m12*B.m52;

               MR.m20 += A.m20*B.m00 + A.m21*B.m01 + A.m22*B.m02;
               MR.m21 += A.m20*B.m10 + A.m21*B.m11 + A.m22*B.m12;
               MR.m22 += A.m20*B.m20 + A.m21*B.m21 + A.m22*B.m22;
               MR.m23 += A.m20*B.m30 + A.m21*B.m31 + A.m22*B.m32;
               MR.m24 += A.m20*B.m40 + A.m21*B.m41 + A.m22*B.m42;
               MR.m25 += A.m20*B.m50 + A.m21*B.m51 + A.m22*B.m52;

               MR.m30 += A.m30*B.m00 + A.m31*B.m01 + A.m32*B.m02;
               MR.m31 += A.m30*B.m10 + A.m31*B.m11 + A.m32*B.m12;
               MR.m32 += A.m30*B.m20 + A.m31*B.m21 + A.m32*B.m22;
               MR.m33 += A.m30*B.m30 + A.m31*B.m31 + A.m32*B.m32;
               MR.m34 += A.m30*B.m40 + A.m31*B.m41 + A.m32*B.m42;
               MR.m35 += A.m30*B.m50 + A.m31*B.m51 + A.m32*B.m52;

               MR.m40 += A.m40*B.m00 + A.m41*B.m01 + A.m42*B.m02;
               MR.m41 += A.m40*B.m10 + A.m41*B.m11 + A.m42*B.m12;
               MR.m42 += A.m40*B.m20 + A.m41*B.m21 + A.m42*B.m22;
               MR.m43 += A.m40*B.m30 + A.m41*B.m31 + A.m42*B.m32;
               MR.m44 += A.m40*B.m40 + A.m41*B.m41 + A.m42*B.m42;
               MR.m45 += A.m40*B.m50 + A.m41*B.m51 + A.m42*B.m52;

               MR.m50 += A.m50*B.m00 + A.m51*B.m01 + A.m52*B.m02;
               MR.m51 += A.m50*B.m10 + A.m51*B.m11 + A.m52*B.m12;
               MR.m52 += A.m50*B.m20 + A.m51*B.m21 + A.m52*B.m22;
               MR.m53 += A.m50*B.m30 + A.m51*B.m31 + A.m52*B.m32;
               MR.m54 += A.m50*B.m40 + A.m51*B.m41 + A.m52*B.m42;
               MR.m55 += A.m50*B.m50 + A.m51*B.m51 + A.m52*B.m52;
               break;
            }
            case 6: {
               Matrix6dBase A = (Matrix6dBase)M1;
               Matrix6dBase B = (Matrix6dBase)M2;

               double t00 = (A.m00*B.m00 + A.m01*B.m01 + A.m02*B.m02 +
                             A.m03*B.m03 + A.m04*B.m04 + A.m05*B.m05);
               double t01 = (A.m00*B.m10 + A.m01*B.m11 + A.m02*B.m12 +
                             A.m03*B.m13 + A.m04*B.m14 + A.m05*B.m15);
               double t02 = (A.m00*B.m20 + A.m01*B.m21 + A.m02*B.m22 +
                             A.m03*B.m23 + A.m04*B.m24 + A.m05*B.m25);
               double t03 = (A.m00*B.m30 + A.m01*B.m31 + A.m02*B.m32 +
                             A.m03*B.m33 + A.m04*B.m34 + A.m05*B.m35);
               double t04 = (A.m00*B.m40 + A.m01*B.m41 + A.m02*B.m42 +
                             A.m03*B.m43 + A.m04*B.m44 + A.m05*B.m45);
               double t05 = (A.m00*B.m50 + A.m01*B.m51 + A.m02*B.m52 +
                             A.m03*B.m53 + A.m04*B.m54 + A.m05*B.m55);

               double t10 = (A.m10*B.m00 + A.m11*B.m01 + A.m12*B.m02 +
                             A.m13*B.m03 + A.m14*B.m04 + A.m15*B.m05);
               double t11 = (A.m10*B.m10 + A.m11*B.m11 + A.m12*B.m12 +
                             A.m13*B.m13 + A.m14*B.m14 + A.m15*B.m15);
               double t12 = (A.m10*B.m20 + A.m11*B.m21 + A.m12*B.m22 +
                             A.m13*B.m23 + A.m14*B.m24 + A.m15*B.m25);
               double t13 = (A.m10*B.m30 + A.m11*B.m31 + A.m12*B.m32 +
                             A.m13*B.m33 + A.m14*B.m34 + A.m15*B.m35);
               double t14 = (A.m10*B.m40 + A.m11*B.m41 + A.m12*B.m42 +
                             A.m13*B.m43 + A.m14*B.m44 + A.m15*B.m45);
               double t15 = (A.m10*B.m50 + A.m11*B.m51 + A.m12*B.m52 +
                             A.m13*B.m53 + A.m14*B.m54 + A.m15*B.m55);

               double t20 = (A.m20*B.m00 + A.m21*B.m01 + A.m22*B.m02 +
                             A.m23*B.m03 + A.m24*B.m04 + A.m25*B.m05);
               double t21 = (A.m20*B.m10 + A.m21*B.m11 + A.m22*B.m12 +
                             A.m23*B.m13 + A.m24*B.m14 + A.m25*B.m15);
               double t22 = (A.m20*B.m20 + A.m21*B.m21 + A.m22*B.m22 +
                             A.m23*B.m23 + A.m24*B.m24 + A.m25*B.m25);
               double t23 = (A.m20*B.m30 + A.m21*B.m31 + A.m22*B.m32 +
                             A.m23*B.m33 + A.m24*B.m34 + A.m25*B.m35);
               double t24 = (A.m20*B.m40 + A.m21*B.m41 + A.m22*B.m42 +
                             A.m23*B.m43 + A.m24*B.m44 + A.m25*B.m45);
               double t25 = (A.m20*B.m50 + A.m21*B.m51 + A.m22*B.m52 +
                             A.m23*B.m53 + A.m24*B.m54 + A.m25*B.m55);

               double t30 = (A.m30*B.m00 + A.m31*B.m01 + A.m32*B.m02 +
                             A.m33*B.m03 + A.m34*B.m04 + A.m35*B.m05);
               double t31 = (A.m30*B.m10 + A.m31*B.m11 + A.m32*B.m12 +
                             A.m33*B.m13 + A.m34*B.m14 + A.m35*B.m15);
               double t32 = (A.m30*B.m20 + A.m31*B.m21 + A.m32*B.m22 +
                             A.m33*B.m23 + A.m34*B.m24 + A.m35*B.m25);
               double t33 = (A.m30*B.m30 + A.m31*B.m31 + A.m32*B.m32 +
                             A.m33*B.m33 + A.m34*B.m34 + A.m35*B.m35);
               double t34 = (A.m30*B.m40 + A.m31*B.m41 + A.m32*B.m42 +
                             A.m33*B.m43 + A.m34*B.m44 + A.m35*B.m45);
               double t35 = (A.m30*B.m50 + A.m31*B.m51 + A.m32*B.m52 +
                             A.m33*B.m53 + A.m34*B.m54 + A.m35*B.m55);

               double t40 = (A.m40*B.m00 + A.m41*B.m01 + A.m42*B.m02 +
                             A.m43*B.m03 + A.m44*B.m04 + A.m45*B.m05);
               double t41 = (A.m40*B.m10 + A.m41*B.m11 + A.m42*B.m12 +
                             A.m43*B.m13 + A.m44*B.m14 + A.m45*B.m15);
               double t42 = (A.m40*B.m20 + A.m41*B.m21 + A.m42*B.m22 +
                             A.m43*B.m23 + A.m44*B.m24 + A.m45*B.m25);
               double t43 = (A.m40*B.m30 + A.m41*B.m31 + A.m42*B.m32 +
                             A.m43*B.m33 + A.m44*B.m34 + A.m45*B.m35);
               double t44 = (A.m40*B.m40 + A.m41*B.m41 + A.m42*B.m42 +
                             A.m43*B.m43 + A.m44*B.m44 + A.m45*B.m45);
               double t45 = (A.m40*B.m50 + A.m41*B.m51 + A.m42*B.m52 +
                             A.m43*B.m53 + A.m44*B.m54 + A.m45*B.m55);

               double t50 = (A.m50*B.m00 + A.m51*B.m01 + A.m52*B.m02 +
                             A.m53*B.m03 + A.m54*B.m04 + A.m55*B.m05);
               double t51 = (A.m50*B.m10 + A.m51*B.m11 + A.m52*B.m12 +
                             A.m53*B.m13 + A.m54*B.m14 + A.m55*B.m15);
               double t52 = (A.m50*B.m20 + A.m51*B.m21 + A.m52*B.m22 +
                             A.m53*B.m23 + A.m54*B.m24 + A.m55*B.m25);
               double t53 = (A.m50*B.m30 + A.m51*B.m31 + A.m52*B.m32 +
                             A.m53*B.m33 + A.m54*B.m34 + A.m55*B.m35);
               double t54 = (A.m50*B.m40 + A.m51*B.m41 + A.m52*B.m42 +
                             A.m53*B.m43 + A.m54*B.m44 + A.m55*B.m45);
               double t55 = (A.m50*B.m50 + A.m51*B.m51 + A.m52*B.m52 +
                             A.m53*B.m53 + A.m54*B.m54 + A.m55*B.m55);

               MR.m00 += t00;
               MR.m01 += t01;
               MR.m02 += t02;
               MR.m03 += t03;
               MR.m04 += t04;
               MR.m05 += t05;

               MR.m10 += t10;
               MR.m11 += t11;
               MR.m12 += t12;
               MR.m13 += t13;
               MR.m14 += t14;
               MR.m15 += t15;

               MR.m20 += t20;
               MR.m21 += t21;
               MR.m22 += t22;
               MR.m23 += t23;
               MR.m24 += t24;
               MR.m25 += t25;

               MR.m30 += t30;
               MR.m31 += t31;
               MR.m32 += t32;
               MR.m33 += t33;
               MR.m34 += t34;
               MR.m35 += t35;

               MR.m40 += t40;
               MR.m41 += t41;
               MR.m42 += t42;
               MR.m43 += t43;
               MR.m44 += t44;
               MR.m45 += t45;

               MR.m50 += t50;
               MR.m51 += t51;
               MR.m52 += t52;
               MR.m53 += t53;
               MR.m54 += t54;
               MR.m55 += t55;
               break;
            }
         }
      }
      else {
         for (int k=0; k<M1.colSize(); k++) {
            MR.m00 += M1.get(0,k)*M2.get(0,k);
            MR.m01 += M1.get(0,k)*M2.get(1,k);
            MR.m02 += M1.get(0,k)*M2.get(2,k);
            MR.m03 += M1.get(0,k)*M2.get(3,k);
            MR.m04 += M1.get(0,k)*M2.get(4,k);
            MR.m05 += M1.get(0,k)*M2.get(5,k);

            MR.m10 += M1.get(1,k)*M2.get(0,k);
            MR.m11 += M1.get(1,k)*M2.get(1,k);
            MR.m12 += M1.get(1,k)*M2.get(2,k);
            MR.m13 += M1.get(1,k)*M2.get(3,k);
            MR.m14 += M1.get(1,k)*M2.get(4,k);
            MR.m15 += M1.get(1,k)*M2.get(5,k);

            MR.m20 += M1.get(2,k)*M2.get(0,k);
            MR.m21 += M1.get(2,k)*M2.get(1,k);
            MR.m22 += M1.get(2,k)*M2.get(2,k);
            MR.m23 += M1.get(2,k)*M2.get(3,k);
            MR.m24 += M1.get(2,k)*M2.get(4,k);
            MR.m25 += M1.get(2,k)*M2.get(5,k);

            MR.m30 += M1.get(3,k)*M2.get(0,k);
            MR.m31 += M1.get(3,k)*M2.get(1,k);
            MR.m32 += M1.get(3,k)*M2.get(2,k);
            MR.m33 += M1.get(3,k)*M2.get(3,k);
            MR.m34 += M1.get(3,k)*M2.get(4,k);
            MR.m35 += M1.get(3,k)*M2.get(5,k);

            MR.m40 += M1.get(4,k)*M2.get(0,k);
            MR.m41 += M1.get(4,k)*M2.get(1,k);
            MR.m42 += M1.get(4,k)*M2.get(2,k);
            MR.m43 += M1.get(4,k)*M2.get(3,k);
            MR.m44 += M1.get(4,k)*M2.get(4,k);
            MR.m45 += M1.get(4,k)*M2.get(5,k);

            MR.m50 += M1.get(5,k)*M2.get(0,k);
            MR.m51 += M1.get(5,k)*M2.get(1,k);
            MR.m52 += M1.get(5,k)*M2.get(2,k);
            MR.m53 += M1.get(5,k)*M2.get(3,k);
            MR.m54 += M1.get(5,k)*M2.get(4,k);
            MR.m55 += M1.get(5,k)*M2.get(5,k);
         }
      }
   }

}
