ROOT_DIR = ../../../..
PACKAGE_NAME = artisynth.core.fields

JAVA_SUBDIRS =

PACKAGE_JAVA_FILES = 

JAVA_TEST_PROGRAMS = \
	MeshFieldTest \
	FemFieldTest \
	GridFieldTest

default: build

-include $(ROOT_DIR)/Makefile.base
