ROOT_DIR = ../../../..
PACKAGE_NAME = artisynth.core.femmodels

JAVA_SUBDIRS = 

PACKAGE_JAVA_FILES = 

default: build

JAVA_TEST_PROGRAMS = \
	DirectorFrameAttachmentTest \
	FemElement3dBaseTest \
	FrameFem3dAttachmentTest \
	FrameNodeNodeAttachmentTest \
	NaturalCoordsComputeTest \
	NodeFrameNodeAttachmentTest \
	PointFem3dAttachmentTest \
	QuadhexElementTest \
	QuadpyramidElementTest \
	QuadwedgeElementTest \
	FemSkinDerivTest

#	AnsysReaderWriterTest \
#	FemModel3dTest \


-include $(ROOT_DIR)/Makefile.base
