ROOT_DIR = ../../../..
PACKAGE_NAME = artisynth.core.femmodels

JAVA_SUBDIRS = materials

PACKAGE_JAVA_FILES = 

default: build

JAVA_TEST_PROGRAMS = \
	AnsysReaderWriterTest

-include $(ROOT_DIR)/Makefile.base
