ROOT_DIR = ../../..
PACKAGE_NAME = maspack.solvers

PACKAGE_JAVA_FILES = 

JAVA_TEST_PROGRAMS = \
	KKTSolverTest \
	KellerLCPSolverTest \
	LemkeContactSolverTest \
	PardisoSolverTest \
	CGSolverTest \
	CRSolverTest

OTHER_CLASSES = 

default: build

CLASSES:: $(PACKAGE_CLASSES) $(OTHER_CLASSES)

-include $(ROOT_DIR)/Makefile.base

